/**
 * Emoji categories with localized titles and search tags
 */

export type EmojiCategory = {
  key: string;
  icon: string;
  title: string;
  titleEn?: string;
  tags: string[];
  tagsEn?: string[];
  emojis: string[];
};

export const CYBLIGHT_EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    key: 'smileys',
    icon: '🙂',
    title: 'Смайлы',
    titleEn: 'Smileys',
    tags: ['улыбка', 'лица', 'эмоции'],
    tagsEn: ['smile', 'face', 'emotion', 'happy', 'sad'],
    emojis: [
      '😀',
      '😃',
      '😄',
      '😁',
      '😆',
      '😅',
      '🤣',
      '😂',
      '🙂',
      '😉',
      '😊',
      '😇',
      '😋',
      '😛',
      '😜',
      '😎',
      '🤓',
      '🧐',
      '🤔',
      '🤨',
      '😐',
      '😑',
      '🙄',
      '😴',
      '😢',
      '😭',
      '😡',
      '🤯',
      '😱',
    ],
  },
  {
    key: 'love',
    icon: '😍',
    title: 'Любовь',
    titleEn: 'Love',
    tags: ['сердце', 'любовь', 'романтика'],
    tagsEn: ['love', 'heart', 'romance', 'kiss'],
    emojis: [
      '😍',
      '🥰',
      '😘',
      '❤️',
      '🧡',
      '💛',
      '💚',
      '💙',
      '💜',
      '🖤',
      '🤍',
      '🤎',
      '💔',
      '❣️',
      '💕',
      '💞',
      '💓',
      '💗',
      '💖',
    ],
  },
  {
    key: 'fire',
    icon: '🔥',
    title: 'Актив',
    titleEn: 'Energy',
    tags: ['огонь', 'топ', 'эмоции'],
    tagsEn: ['fire', 'hot', 'party', 'sparkle', 'energy'],
    emojis: [
      '🔥',
      '✨',
      '⭐',
      '🌟',
      '💫',
      '💥',
      '💯',
      '🎉',
      '🎊',
      '🎈',
      '🎁',
      '🏆',
      '🥇',
      '🥈',
      '🥉',
      '🏅',
    ],
  },
  {
    key: 'sports',
    icon: '⚽️',
    title: 'Спорт',
    titleEn: 'Sports',
    tags: ['спорт', 'игра', 'мяч'],
    tagsEn: ['sport', 'game', 'ball', 'football', 'basketball'],
    emojis: ['⚽️', '🏀', '🏈', '⚾️', '🎾', '🏐', '🏓', '🏸', '🥊', '🥋', '⛳️', '🏒', '🏑', '🎯'],
  },
  {
    key: 'food',
    icon: '🍔',
    title: 'Еда',
    titleEn: 'Food',
    tags: ['еда', 'напитки', 'кухня'],
    tagsEn: ['food', 'drink', 'eat', 'burger', 'pizza', 'coffee', 'sushi'],
    emojis: [
      '🍔',
      '🍕',
      '🍟',
      '🌭',
      '🌮',
      '🍣',
      '🍜',
      '🍿',
      '🍪',
      '🍩',
      '🍫',
      '🍓',
      '🍎',
      '🍇',
      '🥑',
      '☕️',
      '🧋',
    ],
  },
  {
    key: 'travel',
    icon: '🚗',
    title: 'Транспорт',
    titleEn: 'Travel',
    tags: ['транспорт', 'путешествия', 'дорога'],
    tagsEn: ['travel', 'car', 'transport', 'road', 'trip'],
    emojis: [
      '🚗',
      '🚕',
      '🚙',
      '🚌',
      '🚎',
      '🏎️',
      '🚓',
      '🚑',
      '🚒',
      '🚚',
      '🚲',
      '✈️',
      '🚆',
      '🚇',
      '🚢',
      '🚀',
    ],
  },
  {
    key: 'objects',
    icon: '💡',
    title: 'Объекты',
    titleEn: 'Objects',
    tags: ['объекты', 'вещи', 'идеи'],
    tagsEn: ['objects', 'idea', 'tools', 'tech', 'light'],
    emojis: [
      '💡',
      '🔦',
      '📱',
      '💻',
      '⌚️',
      '🎧',
      '📷',
      '🎮',
      '🔧',
      '⚙️',
      '🔒',
      '🔑',
      '🧠',
      '📌',
      '📎',
      '📝',
    ],
  },
  {
    key: 'flags',
    icon: '🏳️',
    title: 'Флаги',
    titleEn: 'Flags',
    tags: ['флаги', 'страны'],
    tagsEn: ['flag', 'flags', 'country', 'nation'],
    emojis: ['🏳️', '🏴', '🏁', '🚩', '🇺🇦', '🇺🇸', '🇬🇧', '🇩🇪', '🇫🇷', '🇮🇹', '🇪🇸', '🇵🇱', '🇯🇵', '🇨🇦'],
  },
];
