/** Auto-generated — run: node scripts/build-supplemental-triples.mjs */
export const supplementalTriples = [
  [" и код 2FA", " та код 2FA", " and 2FA code"],
  ["(ESC для отмены)", "(ESC для скасування)", "(ESC to cancel)"],
  ["-33% Хит", "-33% Хіт", "-33% Hot"],
  ["1 Год", "1 Рік", "1 Year"],
  ["1 Год Premium & Пасхалка открыта! ⏳", "1 Рік Premium & Великодку відкрито! ⏳", "1 Year Premium & Easter Egg Unlocked! ⏳"],
  ["1 Месяц", "1 Місяць", "1 Month"],
  ["1 Месяц Premium & Пасхалка открыта! 🚀", "1 Місяць Premium & Великодку відкрито! 🚀", "1 Month Premium & Easter Egg Unlocked! 🚀"],
  ["1 год", "1 рік", "1 year"],
  ["1 месяц", "1 місяць", "1 month"],
  ["1 неделя", "1 тиждень", "1 week"],
  ["1 спецсимвол (например ! $ ! @ % &)", "1 спецсимвол (наприклад ! $ ! @ % &)", "1 special character (e.g. ! $ ! @ % &)"],
  ["10x Лимиты", "10x Ліміти", "10x Limits"],
  ["10x лимиты API, безлимитный SmartHome Hub, эксклюзивные темы, 2.5x монет и VIP-комнаты", "10x ліміти API, безлімітний SmartHome Hub, ексклюзивні теми, 2.5x монет та VIP-кімнати", "10x API limits, unlimited SmartHome Hub, exclusive themes, 2.5x coins and VIP rooms"],
  ["2FA включена ✅", "2FA увімкнена ✅", "2FA enabled ✅"],
  ["2FA код", "2FA код", "2FA code"],
  ["2FA отключена", "2FA вимкнена", "2FA disabled"],
  ["2FA успешно активирована!", "2FA успішно активовано!", "2FA activated successfully!"],
  ["3 месяца", "3 місяці", "3 months"],
  ["6 Месяцев", "6 Місяців", "6 Months"],
  ["6 Месяцев Premium & Пасхалка открыта! 🛡️", "6 Місяців Premium & Великодку відкрито! 🛡️", "6 Months Premium & Easter Egg Unlocked! 🛡️"],
  ["6 месяцев", "6 місяців", "6 months"],
  ["Beta тестер", "Beta тестер", "Beta tester"],
  ["CybLight - Резервные коды двухфакторной аутентификации", "CybLight - Резервні коди двофакторної автентифікації", "CybLight - Two-factor authentication backup codes"],
  ["Email не указан", "Email не вказано", "Email not set"],
  ["Email подтвержден", "Email підтверджено", "Email confirmed"],
  ["Email подтверждён", "Email підтверджено", "Email confirmed"],
  ["Email сохранён ✅ Письмо отправлено.", "Email збережено ✅ Лист надіслано.", "Email saved ✅ Message sent."],
  ["Email сохранён ✅ Письмо уже отправляли недавно.", "Email збережено ✅ Лист уже надсилали недавно.", "Email saved ✅ A message was already sent recently."],
  ["Email уже подтверждён ✅", "Email уже підтверджено ✅", "Email already confirmed ✅"],
  ["Email-уведомления", "Email-повідомлення", "Email notifications"],
  ["Google Drive или файл .cyblight-backup", "Google Drive або файл .cyblight-backup", "Google Drive or .cyblight-backup file"],
  ["Google Drive не настроен на этом сервере.", "Google Drive не налаштовано на цьому сервері.", "Google Drive is not configured on this server."],
  ["ID пользователя", "ID користувача", "User ID"],
  ["Lifetime VIP & Высшая пасхалка открыта! 🌌👑", "Lifetime VIP & Найвищу великодку відкрито! 🌌👑", "Lifetime VIP & Supreme Easter Egg Unlocked! 🌌👑"],
  ["Passkeys на localhost работают только через http://localhost, а не http://127.0.0.1. Откройте сайт по адресу http://localhost:3000", "Passkeys на localhost працюють лише через http://localhost, а не http://127.0.0.1. Відкрийте сайт за адресою http://localhost:3000", "Passkeys on localhost only work via http://localhost, not http://127.0.0.1. Open the site at http://localhost:3000"],
  ["QR библиотека не загружена. Используй секретный ключ.", "QR бібліотеку не завантажено. Використай секретний ключ.", "QR library not loaded. Use the secret key."],
  ["{amount} ГБ", "{amount} ГБ", "{amount} GB"],
  ["{amount} КБ", "{amount} КБ", "{amount} KB"],
  ["{amount} МБ", "{amount} МБ", "{amount} MB"],
  ["{current} из {total}", "{current} з {total}", "{current} of {total}"],
  ["{current} из {total} сек", "{current} з {total} сек", "{current} of {total} sec"],
  ["{found} из {total}", "{found} з {total}", "{found} of {total}"],
  ["{found} из {total} получено", "{found} з {total} отримано", "{found} of {total} collected"],
  ["{hours} ч {minutes} мин", "{hours} год {minutes} хв", "{hours} h {minutes} min"],
  ["{minutes} мин", "{minutes} хв", "{minutes} min"],
  ["{name} удалён из друзей", "{name} видалено з друзів", "{name} removed from friends"],
  ["Аватар", "Аватар", "Avatar"],
  ["Автозавершение сессий", "Автозавершення сесій", "Automatic session termination"],
  ["Автоматически завершать сессии", "Автоматично завершувати сесії", "Automatically terminate sessions"],
  ["Администратор", "Адміністратор", "Administrator"],
  ["Администрация CybLight не несет ответственности за содержимое, безопасность и политику конфиденциальности сторонних ресурсов.", "Адміністрація CybLight не несе відповідальності за вміст, безпеку та політику конфіденційності сторонніх ресурсів.", "CybLight administration is not responsible for the content, security, or privacy policies of third-party resources."],
  ["Адрес сменится на", "Адресу зміниться на", "Address will change to"],
  ["Адрес электронной почты", "Адреса електронної пошти", "Email address"],
  ["Аккаунт", "Акаунт", "Account"],
  ["Аккаунт Google: {account}", "Обліковий запис Google: {account}", "Google account: {account}"],
  ["Активна", "Активна", "Active"],
  ["Активные сессии", "Активні сесії", "Active sessions"],
  ["Активный", "Активний", "Active"],
  ["Активных сессий:", "Активних сесій:", "Active sessions:"],
  ["Архивариус", "Архіваріус", "Archivist"],
  ["Базовый период", "Базовий період", "Base period"],
  ["Без форматирования", "Без форматування", "Plain text"],
  ["Безвозвратно удалит ваш профиль, переписку, друзей и все данные. Это действие нельзя отменить.", "Безповоротно видалить ваш профіль, листування, друзів та всі дані. Цю дію не можна скасувати.", "Permanently deletes your profile, messages, friends, and all data. This action cannot be undone."],
  ["Безлимитный Hub", "Безлімітний Hub", "Unlimited Hub"],
  ["Безлимитный SmartHome Hub", "Безлімітний SmartHome Hub", "Unlimited SmartHome Hub"],
  ["Безопасная оплата", "Безпечна оплата", "Secure payment"],
  ["Бессрочно (⭐ Premium)", "Безстроково (⭐ Premium)", "Lifetime (⭐ Premium)"],
  ["Бессрочный доступ", "Безстроковий доступ", "Lifetime access"],
  ["Бессрочный доступ (VIP Lifetime)", "Безстроковий доступ (VIP Lifetime)", "Lifetime access (VIP Lifetime)"],
  ["Бессрочный статус Lifetime VIP и полный доступ ко всем возможностям CybLight 🌌👑", "Безстроковий статус Lifetime VIP і повний доступ до всіх можливостей CybLight 🌌👑", "Lifetime VIP status and full access to all CybLight features forever 🌌👑"],
  ["Биометрия должна узнать тебя наизусть", "Біометрія має знати тебе напамʼять", "Biometrics must know you by heart"],
  ["Блок кода (Ctrl+Shift+C)", "Блок коду (Ctrl+Shift+C)", "Code block (Ctrl+Shift+C)"],
  ["Бусинвальд", "Бусинвальд", "Businwald"],
  ["Был(а) {count} дн назад", "Був(ла) {count} дн тому", "Was active {count} d ago"],
  ["Был(а) {count} мин назад", "Був(ла) {count} хв тому", "Was active {count} m ago"],
  ["Был(а) {count} ч назад", "Був(ла) {count} год тому", "Was active {count} h ago"],
  ["Был(а) только что", "Був(ла) щойно", "Was active just now"],
  ["Быстрые", "Швидкі", "Quick"],
  ["В Google Drive нет резервной копии для удаления.", "У Google Drive немає резервної копії для видалення.", "No backup in Google Drive to delete."],
  ["В Google Drive нет резервной копии для этого аккаунта.", "У Google Drive немає резервної копії для цього облікового запису.", "No backup found in Google Drive for this account."],
  ["В один день открыл секрет на сайте и в приложении", "За один день відкрив секрет на сайті й у додатку", "Unlocked a secret on the site and in the app in one day"],
  ["В один день отправил форматированное сообщение на сайте и в приложении", "В один день надіслав форматоване повідомлення на сайті та в додатку", "Sent a formatted message on both site and app on the same day"],
  ["В приложении", "У додатку", "In the app"],
  ["В сети", "В мережі", "Online"],
  ["ВАЖНО: Храните эти коды в безопасном месте!", "ВАЖЛИВО: Зберігайте ці коди в безпечному місці!", "IMPORTANT: Keep these codes in a safe place!"],
  ["Важные уведомления о безопасности и аккаунте", "Важливі повідомлення про безпеку та акаунт", "Important security and account notifications"],
  ["Вам доступны 10x лимиты API, безлимитный SmartHome Hub, эксклюзивные темы, 2.5x монет и кастомный титул.", "Вам доступні 10x ліміти API, безлімітний SmartHome Hub, ексклюзивні теми, 2.5x монет та кастомний титул.", "You have access to 10x API limits, unlimited SmartHome Hub, exclusive themes, 2.5x coins, and a custom badge."],
  ["Вам назначена роль: {role}", "Вам призначено роль: {role}", "You have been assigned the role: {role}"],
  ["Вау, круто!", "Вау, круто!", "Wow, cool!"],
  ["Ваш аккаунт под защитой", "Ваш обліковий запис під захистом", "Your account is protected"],
  ["Ваш аккаунт под надёжной защитой. Рекомендуемых действий не найдено.", "Ваш обліковий запис під надійним захистом. Рекомендованих дій не знайдено.", "Your account is well protected. No recommended actions found."],
  ["Ваш аккаунт прошёл Проверку безопасности", "Ваш обліковий запис пройшов перевірку безпеки", "Your account passed the security check"],
  ["Ваш аккаунт прошёл Проверку безопасности. Рекомендуемых действий не найдено.", "Ваш обліковий запис пройшов перевірку безпеки. Рекомендованих дій не знайдено.", "Your account passed the security check. No recommended actions found."],
  ["Ваш бейдж", "Ваш бейдж", "Your badge"],
  ["Ваш браузер не поддерживает ключи доступа", "Ваш браузер не підтримує ключі доступу", "Your browser does not support passkeys"],
  ["Ваш текущий адрес электронной почты сохранён. Рекомендуем сменить пароль и включить 2FA.", "Вашу поточну адресу електронної пошти збережено. Рекомендуємо змінити пароль і ввімкнути 2FA.", "Your current email address has been kept. We recommend changing your password and enabling 2FA."],
  ["Ваш уникальный логин в системе", "Ваш унікальний логін у системі", "Your unique username in the system"],
  ["Ваша персональная подпись", "Ваш персональний підпис", "Your personal signature"],
  ["Ваши ключи доступа", "Ваші ключі доступу", "Your passkeys"],
  ["Введенные пароли не совпадают.", "Введені паролі не збігаються.", "The entered passwords do not match."],
  ["Введи 6-значный код", "Введи 6-значний код", "Enter the 6-digit code"],
  ["Введи пароль и 6-значный код", "Введи пароль і 6-значний код", "Enter your password and 6-digit code"],
  ["Введите URL:", "Введіть URL:", "Enter URL:"],
  ["Введите email.", "Введіть email.", "Enter email."],
  ["Введите вашу подпись...", "Введіть ваш підпис...", "Enter your signature..."],
  ["Введите действующий пароль.", "Введіть поточний пароль.", "Enter your current password."],
  ["Введите код 2FA", "Введіть код 2FA", "Enter 2FA code"],
  ["Введите корректный адрес электронной почты", "Введіть коректну адресу електронної пошти", "Enter a valid email address"],
  ["Введите название для этого ключа доступа:", "Введіть назву для цього ключа доступу:", "Enter a name for this passkey:"],
  ["Введите новое имя пользователя", "Введіть нове імʼя користувача", "Enter a new username"],
  ["Введите новый пароль еще раз", "Введіть новий пароль ще раз", "Enter the new password again"],
  ["Введите пароль резервной копии", "Введіть пароль резервної копії", "Enter the backup password"],
  ["Введите пароль резервной копии.", "Введіть пароль резервної копії.", "Enter the backup password."],
  ["Введите текущий пароль", "Введіть поточний пароль", "Enter your current password"],
  ["Введите текущий пароль для подтверждения", "Введіть поточний пароль для підтвердження", "Enter your current password to confirm"],
  ["Введите текущий пароль и новый пароль.", "Введіть поточний пароль і новий пароль.", "Enter your current password and new password."],
  ["Великолепно! Вы разгадали секрет бейджа статуса, совершив 5 быстрых тапов, и пробудили звёздную силу CybLight!", "Чудово! Ви розгадали секрет бейджа статусу, зробивши 5 швидких тапів, і пробудили зоряну силу CybLight!", "Magnificent! You solved the status badge secret with 5 quick taps and awakened the stellar power of CybLight!"],
  ["Вернуться", "Повернутися", "Back"],
  ["Ветеран", "Ветеран", "Veteran"],
  ["Взломали аккаунт?", "Зламали обліковий запис?", "Account hacked?"],
  ["Включена", "Увімкнена", "Enabled"],
  ["Включена:", "Увімкнено:", "Enabled:"],
  ["Включите двухфакторную аутентификацию", "Увімкніть двофакторну автентифікацію", "Enable two-factor authentication"],
  ["Включить 2FA", "Увімкнути 2FA", "Enable 2FA"],
  ["Владелец", "Власник", "Owner"],
  ["Властелин бесконечности", "Володар нескінченності", "Infinity Overlord"],
  ["Внешний вид", "Зовнішній вигляд", "Appearance"],
  ["Внимание", "Увага", "Attention"],
  ["Внимание:", "Увага:", "Warning:"],
  ["Войди в аккаунт, чтобы сохранить эту пасхалку.", "Увійди в обліковий запис, щоб зберегти цю пасхалку.", "Sign in to save this easter egg."],
  ["Войдите через Google, чтобы сохранить или восстановить копию.", "Увійдіть через Google, щоб зберегти або відновити копію.", "Sign in with Google to save or restore a backup."],
  ["Войдите, чтобы добавить в друзья", "Увійдіть, щоб додати в друзі", "Sign in to add as friend"],
  ["Войти через Google", "Увійти через Google", "Sign in with Google"],
  ["Восстановить", "Відновити", "Restore"],
  ["Восстановить из Google Drive", "Відновити з Google Drive", "Restore from Google Drive"],
  ["Восстановление из Google Drive", "Відновлення з Google Drive", "Restore from Google Drive"],
  ["Восстановление из Google Drive…", "Відновлення з Google Drive…", "Restoring from Google Drive…"],
  ["Восстановление резервной копии…", "Відновлення резервної копії…", "Restoring backup…"],
  ["Время ожидания синхронизации истекло.", "Час очікування синхронізації закінчився.", "Synchronization timeout."],
  ["Все", "Усі", "All"],
  ["Все настройки Аккаунта", "Усі налаштування Акаунта", "All Account Settings"],
  ["Все получено! 👑", "Усе отримано! 👑", "All collected! 👑"],
  ["Всем", "Усім", "Everyone"],
  ["Вставить", "Вставити", "Insert"],
  ["Вставить ссылку (Ctrl+K)", "Вставить посилання (Ctrl+K)", "Insert link (Ctrl+K)"],
  ["Вход в Google выполнен успешно.", "Вхід у Google виконано успішно.", "Signed in to Google successfully."],
  ["Вход выполнен", "Вхід виконано", "Signed in"],
  ["Вход через Google выполнен", "Вхід через Google виконано", "Signed in with Google"],
  ["Входящие запросы", "Вхідні запити", "Incoming requests"],
  ["Вчера", "Вчора", "Yesterday"],
  ["Вы можете сменить имя пользователя сейчас", "Ви можете змінити ім'я користувача зараз", "You can change your username now"],
  ["Вы открыли секретный неоновый режим редактирования профиля! Аватарки и интерфейс получили квантовое сияние.", "Ви відкрили секретний неоновий режим редагування профілю! Аватарки та інтерфейс отримали квантове сяйво.", "You unlocked the secret neon profile editing mode! Avatars and interface gained quantum luminescence."],
  ["Вы покидаете сайт CybLight и переходите на сторонний ресурс:", "Ви залишаєте сайт CybLight та переходите на сторонній ресурс:", "You are leaving CybLight and proceeding to an external resource:"],
  ["Вы уверены, что хотите удалить {name}?", "Ви впевнені, що хочете видалити {name}?", "Are you sure you want to remove {name}?"],
  ["Вы уже друзья с этим пользователем", "Ви вже друзі з цим користувачем", "You are already friends with this user"],
  ["Выберите валюту оплаты", "Оберіть валюту оплати", "Select payment currency"],
  ["Выберите друга, чтобы начать переписку", "Оберіть друга, щоб почати листування", "Select a friend to start chatting"],
  ["Выберите цветовую тему интерфейса", "Оберіть колірну тему інтерфейсу", "Select interface color theme"],
  ["Выберите язык отображения сайта", "Оберіть мову відображення сайту", "Choose your language"],
  ["Выбор языка", "Вибір мови", "Language selection"],
  ["Выбран некорректный аватар.", "Обрано некоректний аватар.", "Invalid avatar selected."],
  ["Выбрана некорректная рамка аватара.", "Обрано некоректну рамку аватара.", "Invalid avatar frame selected."],
  ["Выбрано: {count}", "Обрано: {count}", "Selected: {count}"],
  ["Выбрать", "Обрати", "Select"],
  ["Выбрать файл и восстановить", "Вибрати файл і відновити", "Choose file and restore"],
  ["Выйти из Google", "Вийти з Google", "Sign out of Google"],
  ["Выполнено", "Виконано", "Done"],
  ["Высший уровень доступа: полное управление проектом CybLight.", "Найвищий рівень доступу: повне керування проєктом CybLight.", "Highest access level: full management of the CybLight project."],
  ["Выход из всех, кроме текущей", "Вихід з усіх, крім поточної", "Sign out of all except current"],
  ["Гость", "Гість", "Guest"],
  ["Готово ✅ Завершено: {count}", "Готово ✅ Завершено: {count}", "Done ✅ Completed: {count}"],
  ["Готовые варианты", "Готові варіанти", "Presets"],
  ["Данные и конфиденциальность", "Дані та конфіденційність", "Data & Privacy"],
  ["Данные получены, применяем…", "Дані отримано, застосовуємо…", "Data received, applying…"],
  ["Дата регистрации", "Дата реєстрації", "Registration date"],
  ["Дата рождения", "Дата народження", "Date of birth"],
  ["Дата создания:", "Дата створення:", "Created:"],
  ["Двухфакторная аутентификация (2FA)", "Двофакторна автентифікація (2FA)", "Two-factor authentication (2FA)"],
  ["Двухфакторная аутентификация активна", "Двофакторна автентифікація активна", "Two-factor authentication is active"],
  ["Двухфакторная аутентификация включена", "Двофакторна автентифікація увімкнена", "Two-factor authentication enabled"],
  ["Двухфакторная аутентификация не активна", "Двофакторна автентифікація не активна", "Two-factor authentication is not active"],
  ["Действие", "Дія", "Action"],
  ["Действует до", "Діє до", "Valid until"],
  ["Действующий пароль", "Поточний пароль", "Current password"],
  ["Длина минимум {min} символов", "Довжина мінімум {min} символів", "At least {min} characters"],
  ["Для вас смена имени пользователя доступна без ограничений!", "Для вас зміна імені користувача доступна без обмежень!", "Username change is available to you with no restrictions!"],
  ["Для отключения введи пароль и текущий 2FA код.", "Для вимкнення введи пароль і поточний 2FA код.", "To disable, enter your password and current 2FA code."],
  ["Добавлено:", "Додано:", "Added:"],
  ["Добавь дополнительный уровень защиты для своего аккаунта.", "Додай додатковий рівень захисту для свого облікового запису.", "Add an extra layer of protection for your account."],
  ["Добавьте еще несколько методов защиты для повышения безопасности.", "Додайте ще кілька методів захисту для підвищення безпеки.", "Add a few more protection methods to improve security."],
  ["Добавьте ключ доступа (Passkey)", "Додайте ключ доступу (Passkey)", "Add a passkey"],
  ["Доверенное устройство", "Довірений пристрій", "Trusted device"],
  ["Доверенные устройства", "Довірені пристрої", "Trusted devices"],
  ["Доверенные устройства для входа с 2FA. Эти устройства не требуют код при входе.", "Довірені пристрої для входу з 2FA. Ці пристрої не потребують коду при вході.", "Trusted devices for 2FA sign-in. These devices do not require a code when signing in."],
  ["Доверенный", "Довірений", "Trusted"],
  ["Докажи преданность системе и стань годовым хранителем сети", "Доведи відданість системі та стань річним хранителем мережі", "Prove your loyalty to the system and become an annual network keeper"],
  ["Дополнительные разделы профиля доступны только друзьям пользователя.", "Додаткові розділи профілю доступні лише друзям користувача.", "Additional profile sections are only visible to the user's friends."],
  ["Доступ к Google Drive не был предоставлен.", "Доступ до Google Drive не було надано.", "Google Drive access was not granted."],
  ["Доступ к инструментам поддержки: помощь пользователям и обработка обращений.", "Доступ до інструментів підтримки: допомога користувачам і обробка звернень.", "Access to support tools: helping users and handling requests."],
  ["Доступ ко всем премиум-темам, стилям оформления и градиентам", "Доступ до всіх преміум-тем, стилів оформлення та градієнтів", "Access to all premium themes, custom styles, and gradients"],
  ["Доступ ограничен. Недостаточно прав для выполнения этого действия.", "Доступ обмежено. Недостатньо прав для виконання цієї дії.", "Access restricted. Insufficient permissions to perform this action."],
  ["Доступно для CybLight Premium", "Доступно для CybLight Premium", "Available for CybLight Premium"],
  ["Если email зарегистрирован, мы отправили вам логин. Проверьте почту (и «Спам»).", "Якщо email зареєстровано, ми надіслали вам логін. Перевірте пошту (і «Спам»).", "If the email is registered, we sent your username. Check your inbox (and Spam)."],
  ["Если email зарегистрирован, мы отправили ссылку для сброса пароля. Проверьте почту (и «Спам»).", "Якщо email зареєстровано, ми надіслали посилання для скидання пароля. Перевірте пошту (і «Спам»).", "If the email is registered, we sent a password reset link. Check your inbox (and Spam)."],
  ["Если сессия неактивна", "Якщо сесія неактивна", "If the session is inactive"],
  ["Женский", "Жіночий", "Female"],
  ["Жирный (Ctrl+B)", "Жирний (Ctrl+B)", "Bold (Ctrl+B)"],
  ["Завершить", "Завершити", "End"],
  ["Загляни в редактирование профиля и прояви свой творческий подход", "Зазирни в редагування профілю та прояви свій творчий підхід", "Take a look into profile editing and show your creative flair"],
  ["Загружаю...", "Завантажую...", "Loading..."],
  ["Загрузка профиля...", "Завантаження профілю...", "Loading profile..."],
  ["Загрузка списка...", "Завантаження списку...", "Loading list..."],
  ["Загрузка статуса…", "Завантаження статусу…", "Loading status…"],
  ["Загрузка…", "Завантаження…", "Loading…"],
  ["Задайте свой персональный титул или бейдж (до 24 символов), который будет отображаться рядом с вашим никнеймом.", "Задайте свій персональний титул або бейдж (до 24 символів), який відображатиметься поруч із вашим нікнеймом.", "Set your custom title or badge (up to 24 characters) to be displayed next to your username."],
  ["Закрепил, изменил, отреагировал и переслал в одном чате", "Закріпив, змінив, відреагував і переслав в одному чаті", "Pinned, edited, reacted, and forwarded in one chat"],
  ["Закреплённое сообщение", "Закріплене повідомлення", "Pinned message"],
  ["Закрыть меню", "Закрити меню", "Close menu"],
  ["Запланирована смена email", "Заплановано зміну email", "Email change scheduled"],
  ["Запомнить пароль и больше не спрашивать", "Запам'ятати пароль і більше не запитувати", "Remember password and do not ask again"],
  ["Запрос на добавление отправлен", "Запит на додавання надіслано", "Friend request sent"],
  ["Запрос на дружбу не найден", "Запит на дружбу не знайдено", "Friend request not found"],
  ["Запрос на смену email принят. Письмо уже отправляли недавно — проверьте почту.", "Запит на зміну email прийнято. Лист уже надсилали недавно — перевірте пошту.", "Email change request accepted. A message was already sent recently — check your inbox."],
  ["Запрос на смену email принят. Подтвердите новый адрес и проверьте текущую почту.", "Запит на зміну email прийнято. Підтвердіть нову адресу й перевірте поточну пошту.", "Email change request accepted. Confirm the new address and check your current inbox."],
  ["Запрос отменён", "Запит скасовано", "Request cancelled"],
  ["Запрос принят", "Запит прийнято", "Request accepted"],
  ["Запрос принят. Письмо с подтверждением уже отправляли недавно — проверьте почту.", "Запит прийнято. Лист із підтвердженням вже надсилали нещодавно — перевірте пошту.", "Request accepted. A confirmation email was sent recently — check your inbox."],
  ["Запросы в друзья", "Запити в друзі", "Friend requests"],
  ["Запрошена смена на", "Запрошено зміну на", "Change requested to"],
  ["Запрошена смена на {email}. Подтвердите письмо на новом адресе.", "Запрошено зміну на {email}. Підтвердіть лист на новій адресі.", "Change requested to {email}. Confirm the message at the new address."],
  ["Зарегистрировано ключей: {count}", "Зареєстровано ключів: {count}", "Registered keys: {count}"],
  ["Зачёркнутый (Ctrl+Shift+X)", "Закреслений (Ctrl+Shift+X)", "Strikethrough (Ctrl+Shift+X)"],
  ["Защищён", "Захищений", "Protected"],
  ["Звёздная искра", "Зоряна іскра", "Star Spark"],
  ["Здесь живет секрет художников...", "Тут живе секрет художників...", "The secret of artists lives here..."],
  ["Зеркало профиля", "Дзеркало профілю", "Profile mirror"],
  ["Зеркало формата", "Дзеркало формату", "Format mirror"],
  ["Золотая", "Золота", "Gold"],
  ["Золотое прикосновение", "Золотий дотик", "Golden Touch"],
  ["Золотой статус Premium", "Золотий статус Premium", "Golden Premium Status"],
  ["Игры", "Ігри", "Games"],
  ["Изменение временно недоступно", "Зміна тимчасово недоступна", "Change temporarily unavailable"],
  ["Изменить", "Змінити", "Change"],
  ["Изменить аккаунт", "Змінити обліковий запис", "Change account"],
  ["Импорт", "Імпорт", "Import"],
  ["Импорт завершён: добавлено {imported}, пропущено {skipped}, ошибок {errors}", "Імпорт завершено: додано {imported}, пропущено {skipped}, помилок {errors}", "Import complete: added {imported}, skipped {skipped}, errors {errors}"],
  ["Импорт чатов", "Імпорт чатів", "Import chats"],
  ["Имя пользователя", "Імʼя користувача", "Username"],
  ["Имя пользователя успешно изменено", "Імʼя користувача успішно змінено", "Username changed successfully"],
  ["Использован:", "Використано:", "Used:"],
  ["Использовано: {used}", "Використано: {used}", "Used: {used}"],
  ["Использовано: {used} из {limit}", "Використано: {used} з {limit}", "Used: {used} of {limit}"],
  ["Используется для входа и уведомлений", "Використовується для входу та повідомлень", "Used for sign-in and notifications"],
  ["Используй приложение Proton , Google , Microsoft Authenticator или Authy.", "Використай додаток Proton, Google, Microsoft Authenticator або Authy.", "Use Proton, Google, Microsoft Authenticator, or Authy."],
  ["История", "Історія", "History"],
  ["История входов", "Історія входів", "Sign-in history"],
  ["История входов в аккаунт за последнее время", "Історія входів в обліковий запис за останній час", "Recent account sign-in history"],
  ["История входов пуста", "Історія входів порожня", "Sign-in history is empty"],
  ["История пуста", "Історія порожня", "History is empty"],
  ["Каждый код можно использовать только один раз для входа без доступа к приложению аутентификации.", "Кожен код можна використати лише один раз для входу без доступу до додатка автентифікації.", "Each code can only be used once to sign in without access to the authenticator app."],
  ["Кастомный бейдж успешно сохранен", "Кастомний бейдж успішно збережено", "Custom badge saved successfully"],
  ["Кастомный титул", "Кастомний титул", "Custom title"],
  ["Кастомный титул / бейдж", "Кастомний титул / бейдж", "Custom title / badge"],
  ["Категории пасхалок", "Категорії пасхалок", "Easter egg categories"],
  ["Кибер", "Кібер", "Cyber"],
  ["Кибер-Художник", "Кібер-Художник", "Cyber Artist"],
  ["Киберпанк", "Кіберпанк", "Cyberpunk"],
  ["Ключ доступа", "Ключ доступу", "Passkey"],
  ["Ключ доступа (Passkey) добавлен", "Ключ доступу (Passkey) додано", "Passkey added"],
  ["Ключ доступа удалён", "Ключ доступу видалено", "Passkey removed"],
  ["Ключ доступа успешно добавлен! ✅", "Ключ доступу успішно додано! ✅", "Passkey added successfully! ✅"],
  ["Ключ скопирован ✅", "Ключ скопійовано ✅", "Key copied ✅"],
  ["Ключи доступа (Passkeys)", "Ключі доступу (Passkeys)", "Passkeys"],
  ["Ключи доступа (passkeys) позволяют входить в аккаунт без пароля, используя биометрию или PIN-код устройства.", "Ключі доступу (passkeys) дозволяють входити в обліковий запис без пароля, використовуючи біометрію або PIN-код пристрою.", "Passkeys let you sign in without a password using biometrics or your device PIN."],
  ["Ключи доступа не добавлены", "Ключі доступу не додано", "No passkeys added"],
  ["Ключи не добавлены", "Ключі не додано", "No keys added"],
  ["Ключи шифрования восстановлены. Обновите страницу сообщений.", "Ключі шифрування відновлено. Оновіть сторінку повідомлень.", "Encryption keys restored. Refresh the messages page."],
  ["Ключи шифрования сохранены на другом устройстве. Откройте чат в приложении или в том же браузере, где уже входили.", "Ключі шифрування збережено на іншому пристрої. Відкрийте чат у додатку або в тому ж браузері, де вже входили.", "Encryption keys are stored on another device. Open the chat in the app or in the same browser you used before."],
  ["Ключи шифрования успешно восстановлены из Google Drive.", "Ключі шифрування успішно відновлено з Google Drive.", "Encryption keys successfully restored from Google Drive."],
  ["Ключи шифрования успешно восстановлены. Сообщения пропущены.", "Ключі шифрування успішно відновлено. Повідомлення пропущено.", "Encryption keys successfully restored. Messages skipped."],
  ["Когда кто-то захочет добавить вас в друзья, запрос появится здесь", "Коли хтось захоче додати вас у друзі, запит зʼявиться тут", "When someone wants to add you as a friend, the request will appear here"],
  ["Код 2FA", "Код 2FA", "2FA code"],
  ["Код двухфакторной аутентификации", "Код двофакторної автентифікації", "Two-factor authentication code"],
  ["Коды скопированы ✅", "Коди скопійовано ✅", "Codes copied ✅"],
  ["Количество друзей", "Кількість друзів", "Friends count"],
  ["Кому видно:", "Кому видно:", "Visible to:"],
  ["Конфиденциальность", "Конфіденційність", "Privacy"],
  ["Конфликт ключей шифрования в этом браузере. Очистите данные сайта или сбросьте ключи в настройках.", "Конфлікт ключів шифрування в цьому браузері. Очистіть дані сайту або скиньте ключі в налаштуваннях.", "Encryption key conflict in this browser. Clear site data or reset keys in settings."],
  ["Копируйте ссылку:", "Копіюйте посилання:", "Copy the link:"],
  ["Кто может видеть мою подпись", "Хто може бачити мій підпис", "Who can see my signature"],
  ["Кто может видеть список и количество моих друзей", "Хто може бачити список і кількість моїх друзів", "Who can see my friend list and friend count"],
  ["Курсив (Ctrl+I)", "Курсив (Ctrl+I)", "Italic (Ctrl+I)"],
  ["Ловец света", "Ловець світла", "Light Catcher"],
  ["Максимальная выгода", "Максимальна вигода", "Best value"],
  ["Максимум возможностей для вашего аккаунта", "Максимум можливостей для вашого акаунта", "Maximum capabilities for your account"],
  ["Маятник", "Гойдалка", "Pendulum"],
  ["Мгновенная доставка сигналов и облачных бэкапов", "Миттєва доставка сигналів та хмарних бекапів", "Instant signal delivery and cloud backups"],
  ["Меню пользователя", "Меню користувача", "User menu"],
  ["Местоположение", "Місцезнаходження", "Location"],
  ["Минимум 8 символов. Запомните пароль — без него нельзя восстановить ключи.", "Мінімум 8 символів. Запамʼятайте пароль — без нього не можна відновити ключі.", "At least 8 characters. Remember the password — you cannot restore keys without it."],
  ["Модератор", "Модератор", "Moderator"],
  ["Модерация контента и соблюдение правил на платформе.", "Модерація контенту та дотримання правил на платформі.", "Content moderation and enforcing platform rules."],
  ["Можно изменить через {days} дней", "Можна змінити через {days} днів", "Can be changed in {days} days"],
  ["Мои друзья", "Мої друзі", "My friends"],
  ["Мой ключ", "Мій ключ", "My key"],
  ["Мой профиль", "Мій профіль", "My profile"],
  ["Моноширинный (Ctrl+Shift+M)", "Моноширинний (Ctrl+Shift+M)", "Monospace (Ctrl+Shift+M)"],
  ["Мост", "Міст", "Bridge"],
  ["Мужской", "Чоловічий", "Male"],
  ["На CybLight с", "На CybLight з", "On CybLight since"],
  ["На главную", "На головну", "Home"],
  ["На сайте", "На сайті", "On the website"],
  ["На указанный адрес отправлено письмо для подтверждения смены email.", "На вказану адресу надіслано лист для підтвердження зміни email.", "A confirmation email has been sent to the specified address."],
  ["Навигация аккаунта", "Навігація облікового запису", "Account navigation"],
  ["Навигация по настройкам", "Навігація по налаштуваннях", "Settings navigation"],
  ["Навсегда", "Назавжди", "Lifetime"],
  ["Нажмите, чтобы открыть управление хранилищем Google", "Натисніть, щоб відкрити керування сховищем Google", "Click to open Google storage management"],
  ["Нажмите, чтобы открыть чат", "Натисніть, щоб відкрити чат", "Click to open chat"],
  ["Найди пасхалки и на сайте, и в приложении в один день", "Знайди пасхалки й на сайті, й у додатку за один день", "Find easter eggs on the site and in the app in one day"],
  ["Найди спрятанную клубничку где-то там...", "Знайди приховану полуничку десь там...", "Find the hidden strawberry somewhere..."],
  ["Найдите пользователей и добавьте их в друзья", "Знайдіть користувачів і додайте їх у друзі", "Find users and add them as friends"],
  ["Найдите пользователей и отправьте им запрос в друзья", "Знайдіть користувачів і надішліть їм запит у друзі", "Find users and send them friend requests"],
  ["Настройка видимости вашей подписи в профиле", "Налаштування видимості вашого підпису в профілі", "Configure signature visibility on your profile"],
  ["Настройка видимости ваших друзей в профиле", "Налаштування видимості ваших друзів у профілі", "Configure friends visibility on your profile"],
  ["Настройки обновлены", "Налаштування оновлено", "Settings updated"],
  ["Настройки сообщений", "Налаштування повідомлень", "Message settings"],
  ["Начните с подтверждения email и включения 2FA для базовой защиты аккаунта.", "Почніть з підтвердження email і ввімкнення 2FA для базового захисту облікового запису.", "Start by confirming your email and enabling 2FA for basic account protection."],
  ["Не использовалось", "Не використовувалось", "Never used"],
  ["Не подтверждён", "Не підтверджено", "Not confirmed"],
  ["Не получен", "Не отримано", "Not received"],
  ["Не удалось авторизоваться в Google.", "Не вдалося авторизуватися в Google.", "Failed to authenticate with Google."],
  ["Не удалось войти через Google.", "Не вдалося увійти через Google.", "Could not sign in with Google."],
  ["Не удалось войти. Проверьте пароль или попробуйте позже.", "Не вдалося увійти. Перевірте пароль або спробуйте пізніше.", "Failed to sign in. Check password or try again later."],
  ["Не удалось выполнить поиск", "Не вдалося виконати пошук", "Search failed"],
  ["Не удалось завершить сессию.", "Не вдалося завершити сесію.", "Failed to end session."],
  ["Не удалось загрузить друзей", "Не вдалося завантажити друзів", "Failed to load friends"],
  ["Не удалось загрузить сообщения", "Не вдалося завантажити повідомлення", "Failed to load messages"],
  ["Не удалось загрузить список друзей для пересылки", "Не вдалося завантажити список друзів для пересилання", "Failed to load friends list for forwarding"],
  ["Не удалось изменить пароль.", "Не вдалося змінити пароль.", "Failed to change password."],
  ["Не удалось импортировать чаты из резервной копии.", "Не вдалося імпортувати чати з резервної копії.", "Could not import chats from the backup."],
  ["Не удалось импортировать чаты.", "Не вдалося імпортувати чати.", "Could not import chats."],
  ["Не удалось инициализировать синхронизацию.", "Не вдалося ініціалізувати синхронізацію.", "Failed to initialize synchronization."],
  ["Не удалось обработать резервную копию.", "Не вдалося обробити резервну копію.", "Could not process the backup."],
  ["Не удалось открепить сообщение", "Не вдалося відкріпити повідомлення", "Failed to unpin message"],
  ["Не удалось отменить", "Не вдалося скасувати", "Could not cancel"],
  ["Не удалось отправить письмо.", "Не вдалося надіслати лист.", "Failed to send email."],
  ["Не удалось отправить сообщение", "Не вдалося надіслати повідомлення", "Failed to send message"],
  ["Не удалось отредактировать сообщение", "Не вдалося відредагувати повідомлення", "Failed to edit message"],
  ["Не удалось переслать сообщение", "Не вдалося переслати повідомлення", "Failed to forward message"],
  ["Не удалось скачать резервную копию из Google Drive.", "Не вдалося завантажити резервну копію з Google Drive.", "Could not download the backup from Google Drive."],
  ["Не удалось скопировать. Выдели коды вручную.", "Не вдалося скопіювати. Виділи коди вручну.", "Failed to copy. Select the codes manually."],
  ["Не удалось скопировать. Выдели текст вручную.", "Не вдалося скопіювати. Виділи текст вручну.", "Failed to copy. Select the text manually."],
  ["Не удалось сохранить email.", "Не вдалося зберегти email.", "Failed to save email."],
  ["Не удалось сохранить бейдж", "Не вдалося зберегти бейдж", "Failed to save badge"],
  ["Не удалось сохранить имя пользователя", "Не вдалося зберегти імʼя користувача", "Failed to save username"],
  ["Не удалось сохранить резервную копию в Google Drive.", "Не вдалося зберегти резервну копію в Google Drive.", "Could not save the backup to Google Drive."],
  ["Не удалось удалить резервную копию из Google Drive.", "Не вдалося видалити резервну копію з Google Drive.", "Could not delete the backup from Google Drive."],
  ["Не удалось удалить сообщения", "Не вдалося видалити повідомлення", "Failed to delete messages"],
  ["Не удалось экспортировать чаты.", "Не вдалося експортувати чати.", "Could not export chats."],
  ["Не удалось.", "Не вдалося.", "Failed."],
  ["Не указана", "Не вказана", "Not set"],
  ["Не указано", "Не вказано", "Not specified"],
  ["Не установлен", "Не встановлено", "Not set"],
  ["Неверный 2FA код", "Невірний 2FA код", "Invalid 2FA code"],
  ["Неверный действующий пароль.", "Невірний поточний пароль.", "Invalid current password."],
  ["Неверный логин или пароль. Проверьте введенные данные.", "Невірний логін або пароль. Перевірте введені дані.", "Invalid username or password. Please check your credentials."],
  ["Неверный пароль", "Невірний пароль", "Wrong password"],
  ["Неверный пароль резервной копии.", "Невірний пароль резервної копії.", "Incorrect backup password."],
  ["Недопустимый формат имени пользователя", "Недопустимий формат імені користувача", "Invalid username format"],
  ["Неизвестная ошибка", "Невідома помилка", "Unknown error"],
  ["Некорректный ключ синхронизации в резервной копии.", "Некоректний ключ синхронізації в резервній копії.", "Invalid sync key in the backup."],
  ["Некорректный ответ сервера при экспорте чатов.", "Некоректна відповідь сервера під час експорту чатів.", "Invalid server response while exporting chats."],
  ["Некорректный файл резервной копии.", "Некоректний файл резервної копії.", "Invalid backup file."],
  ["Некорректный файл экспорта чатов.", "Некоректний файл експорту чатів.", "Invalid chat export file."],
  ["Некорректный формат логина. Используйте латинские буквы (A–Z), цифры (0–9) и символ подчеркивания (3–24 символа).", "Некоректний формат логіна. Використовуйте латинські літери (A–Z), цифри (0–9) та символ підкреслення (3–24 символи).", "Invalid username format. Use Latin letters (A–Z), numbers (0–9), and underscore (3–24 characters)."],
  ["Нельзя добавить себя в друзья", "Не можна додати себе в друзі", "You cannot add yourself as a friend"],
  ["Нельзя использовать рус/укр буквы и любые не-ASCII символы.", "Не можна використовувати кирилицю та не-ASCII символи.", "Cyrillic and non-ASCII characters are not allowed."],
  ["Нельзя удалять чужие сообщения", "Не можна видаляти чужі повідомлення", "You cannot delete other people's messages"],
  ["Необратимые действия — будьте осторожны", "Незворотні дії — будьте обережні", "Irreversible actions — please be careful"],
  ["Неограниченные комнаты, устройства Tapo и Wake-on-LAN", "Необмежені кімнати, пристрої Tapo та Wake-on-LAN", "Unlimited rooms, Tapo devices, and Wake-on-LAN"],
  ["Неподдерживаемый формат шифрования резервной копии.", "Непідтримуваний формат шифрування резервної копії.", "Unsupported backup encryption format."],
  ["Нет доверенных устройств", "Немає довірених пристроїв", "No trusted devices"],
  ["Нет друзей для пересылки", "Немає друзів для пересилання", "No friends to forward to"],
  ["Нет локальных ключей шифрования для резервной копии.", "Немає локальних ключів шифрування для резервної копії.", "No local encryption keys for backup."],
  ["Нет новых запросов", "Немає нових запитів", "No new requests"],
  ["Нет отправленных запросов", "Немає надісланих запитів", "No sent requests"],
  ["Нет резервной копии", "Немає резервної копії", "No backup found"],
  ["Нет сессий", "Немає сесій", "No sessions"],
  ["Низкая", "Низька", "Low"],
  ["Никому", "Нікому", "Nobody"],
  ["Ничего не найдено", "Нічого не знайдено", "Nothing found"],
  ["Новая роль", "Нова роль", "New role"],
  ["Новичок", "Новачок", "Newcomer"],
  ["Новые пароли не совпадают.", "Нові паролі не збігаються.", "New passwords do not match."],
  ["Новые сообщения", "Нові повідомлення", "New messages"],
  ["Новый email активирован. Все сессии завершены — войдите снова.", "Новий email активовано. Усі сесії завершено — увійдіть знову.", "New email activated. All sessions ended — sign in again."],
  ["Новый email подтверждён", "Новий email підтверджено", "New email confirmed"],
  ["Новый email подтверждён. Смена завершится через 24 часа; до этого действует текущий адрес.", "Новий email підтверджено. Зміну завершиться за 24 години; до цього діє поточна адреса.", "New email confirmed. The change completes in 24 hours; until then the current address applies."],
  ["Новый адрес {email} подтверждён. Смена завершится {date}.", "Нову адресу {email} підтверджено. Зміну завершиться {date}.", "New address {email} confirmed. Change completes {date}."],
  ["Новый адрес почты", "Нова адреса пошти", "New email address"],
  ["Новый пароль должен быть минимум 8 символов.", "Новий пароль має бути мінімум 8 символів.", "New password must be at least 8 characters."],
  ["Новый пароль должен быть только латиницей (ASCII).", "Новий пароль має бути лише латиницею (ASCII).", "New password must use Latin characters only (ASCII)."],
  ["Новый пароль должен отличаться от текущего.", "Новий пароль має відрізнятися від поточного.", "New password must differ from the current one."],
  ["Ночной страж", "Нічний вартовий", "Night Guard"],
  ["Ночь, тёмная тема и 30 секунд терпения", "Ніч, темна тема й 30 секунд терпіння", "Night, dark theme, and 30 seconds of patience"],
  ["О себе", "Про себе", "About me"],
  ["О себе (кратко)", "Про себе (коротко)", "About me (short)"],
  ["ОС", "ОС", "OS"],
  ["Обеспечь полугодовую броню для своего виртуального дома", "Забезпеч піврічну броню для свого віртуального дому", "Secure a half-year armor for your virtual home"],
  ["Обнаружены рекомендации по защите", "Виявлено рекомендації щодо захисту", "Security recommendations found"],
  ["Объявления и важные сообщения от администрации", "Оголошення та важливі повідомлення від адміністрації", "Announcements and critical messages from administration"],
  ["Опасная зона", "Небезпечна зона", "Danger Zone"],
  ["Оплатить через Stripe", "Оплатити через Stripe", "Pay with Stripe"],
  ["Освой все инструменты сообщений в одном диалоге", "Опануй усі інструменти повідомлень в одному діалозі", "Master all message tools in one chat"],
  ["Основное имя для входа", "Основне імʼя для входу", "Primary sign-in name"],
  ["Основные данные вашего аккаунта", "Основні дані вашого акаунту", "Basic info of your account"],
  ["Осталось: {time}", "Залишилось: {time}", "Remaining: {time}"],
  ["Ответ на", "Відповідь на", "Reply to"],
  ["Отключаю...", "Вимикаю...", "Disabling..."],
  ["Отключена", "Вимкнена", "Disabled"],
  ["Отключение 2FA", "Вимкнення 2FA", "Disable 2FA"],
  ["Отключить 2FA", "Вимкнути 2FA", "Disable 2FA"],
  ["Открепить сообщение", "Відкріпити повідомлення", "Unpin message"],
  ["Открыть коллекцию пасхалок", "Відкрити колекцію великодок", "Open Easter Egg Collection"],
  ["Открыть меню", "Відкрити меню", "Open menu"],
  ["Открыть настройки резервной копии", "Відкрити налаштування резервної копії", "Open backup settings"],
  ["Открыть свой профиль", "Відкрити свій профіль", "Open your profile"],
  ["Открыть стенографию", "Відкрити стенографію", "Open stenography"],
  ["Отлично!", "Чудово!", "Great!"],
  ["Отлично! Осталось совсем немного для максимальной защиты.", "Чудово! Залишилось зовсім трохи до максимального захисту.", "Great! Just a little more for maximum protection."],
  ["Отмена смены email", "Скасування зміни email", "Cancel email change"],
  ["Отменено восстановление резервной копии.", "Скасовано відновлення резервної копії.", "Backup restore cancelled."],
  ["Отменить", "Скасувати", "Cancel"],
  ["Отменить ответ", "Скасувати відповідь", "Cancel reply"],
  ["Отменить смену", "Скасувати зміну", "Cancel change"],
  ["Отменяем смену email...", "Скасовуємо зміну email...", "Cancelling email change..."],
  ["Отпечаток доверия", "Відбиток довіри", "Trust print"],
  ["Отправить письмо ещё раз", "Надіслати лист ще раз", "Send email again"],
  ["Отправленные запросы", "Надіслані запити", "Sent requests"],
  ["Отправлено", "Надіслано", "Sent"],
  ["Отправляй его поддержке", "Надсилай його підтримці", "Send it to support"],
  ["Отправляю…", "Надсилаю…", "Sending…"],
  ["Отправь сообщение ровно в 23:59", "Надішли повідомлення рівно о 23:59", "Send a message at exactly 23:59"],
  ["Отсутствует токен. Проверьте ссылку из письма.", "Відсутній токен. Перевірте посилання з листа.", "Missing token. Check the link in your email."],
  ["Отформатируй сообщение и на сайте, и в приложении в один день", "Відформатуй повідомлення і на сайті, і в додатку в один день", "Format a message on both site and app on the same day"],
  ["Оформить от $4.99", "Оформити від $4.99", "Get from $4.99"],
  ["Оформление подписки Premium было отменено.", "Оформлення підписки Premium було скасовано.", "Premium subscription checkout was cancelled."],
  ["Очистить", "Очистити", "Clear"],
  ["Ошибка", "Помилка", "Error"],
  ["Ошибка доступа к локальной базе данных браузера.", "Помилка доступу до локальної бази даних браузера.", "Error accessing local browser database."],
  ["Ошибка загрузки истории", "Помилка завантаження історії", "Failed to load history"],
  ["Ошибка загрузки устройств", "Помилка завантаження пристроїв", "Failed to load devices"],
  ["Ошибка загрузки. Попробуйте обновить страницу.", "Помилка завантаження. Спробуйте оновити сторінку.", "Loading error. Try refreshing the page."],
  ["Ошибка оформления подписки", "Помилка оформлення підписки", "Subscription processing error"],
  ["Ошибка подключения к серверу", "Помилка підключення до сервера", "Server connection error"],
  ["Ошибка получения параметров регистрации", "Помилка отримання параметрів реєстрації", "Failed to get registration parameters"],
  ["Ошибка при обновлении профиля", "Помилка під час оновлення профілю", "Error updating profile"],
  ["Ошибка при отклонении запроса", "Помилка під час відхилення запиту", "Error declining request"],
  ["Ошибка при отмене запроса", "Помилка під час скасування запиту", "Error cancelling request"],
  ["Ошибка при отправке запроса", "Помилка під час надсилання запиту", "Error sending request"],
  ["Ошибка при получении данных.", "Помилка при отриманні даних.", "Error receiving data."],
  ["Ошибка при принятии запроса", "Помилка під час прийняття запиту", "Error accepting request"],
  ["Ошибка при сохранении", "Помилка при збереженні", "Error during saving"],
  ["Ошибка при сохранении профиля", "Помилка під час збереження профілю", "Error saving profile"],
  ["Ошибка при удалении друга", "Помилка під час видалення друга", "Error removing friend"],
  ["Ошибка проверки", "Помилка перевірки", "Verification error"],
  ["Ошибка сети", "Помилка мережі", "Network error"],
  ["Ошибка сети или сервера", "Помилка мережі або сервера", "Network or server error"],
  ["Ошибка сети.", "Помилка мережі.", "Network error."],
  ["Ошибка сохранения", "Помилка збереження", "Saving error"],
  ["Ошибка сохранения ключа:", "Помилка збереження ключа:", "Error saving key:"],
  ["Ошибка удаления", "Помилка видалення", "Deletion error"],
  ["Ошибка удаления ключа", "Помилка видалення ключа", "Error removing key"],
  ["Ошибка:", "Помилка:", "Error:"],
  ["Пароли не совпадают.", "Паролі не збігаються.", "Passwords do not match."],
  ["Пароль для подтверждения", "Пароль для підтвердження", "Password for confirmation"],
  ["Пароль и безопасность", "Пароль та безпека", "Password & Security"],
  ["Пароль изменён ✅", "Пароль змінено ✅", "Password changed ✅"],
  ["Пароль не соответствует требованиям безопасности (минимум 8 символов).", "Пароль не відповідає вимогам безпеки (мінімум 8 символів).", "Password does not meet security requirements (minimum 8 characters)."],
  ["Пароль от резервной копии", "Пароль від резервної копії", "Backup password"],
  ["Пароль от файла резервной копии", "Пароль від файлу резервної копії", "Backup file password"],
  ["Пароль резервной копии", "Пароль резервної копії", "Backup password"],
  ["Пароль резервной копии должен быть не короче 8 символов.", "Пароль резервної копії має бути не коротшим за 8 символів.", "Backup password must be at least 8 characters."],
  ["Пароль успешно изменён ✅", "Пароль успішно змінено ✅", "Password changed successfully ✅"],
  ["Пароль успешно изменён!", "Пароль успішно змінено!", "Password changed successfully!"],
  ["Пароль, заданный при создании резервной копии.", "Пароль, заданий під час створення резервної копії.", "Password set when the backup was created."],
  ["Пароль, заданный при сохранении копии в Google Drive.", "Пароль, заданий під час збереження копії в Google Drive.", "Password set when saving the backup to Google Drive."],
  ["Пасхалка добавлена в вашу коллекцию в профиле.", "Великодку додано до вашої колекції у профілі.", "Easter egg added to your collection in your profile."],
  ["Пасхалка найдена: «Кибер-Художник»!", "Великодку знайдено: «Кібер-Художник»!", "Easter egg found: 'Cyber Artist'!"],
  ["Первый импульс", "Перший імпульс", "First Pulse"],
  ["Перейти в раздел «Безопасность» →", "Перейти в розділ «Безпека» →", "Go to Security →"],
  ["Перейти к сообщению", "Перейти до повідомлення", "Go to message"],
  ["Перейти на сайт", "Перейти на сайт", "Go to website"],
  ["Переслано {count} сообщений", "Переслано {count} повідомлень", "Forwarded {count} messages"],
  ["Переслать сообщение", "Переслати повідомлення", "Forward message"],
  ["Переход к оплате Stripe...", "Перехід до оплати Stripe...", "Redirecting to Stripe..."],
  ["Переход на проверенный ресурс", "Перехід на перевірений ресурс", "Proceed to verified resource"],
  ["Переход по внешней ссылке", "Перехід за зовнішнім посиланням", "External link redirect"],
  ["Персональная подпись в профиле", "Персональний підпис у профілі", "Personal profile signature"],
  ["Письмо отправлено ✅ Проверь почту (и Спам).", "Лист надіслано ✅ Перевір пошту (і Спам).", "Email sent ✅ Check your inbox (and Spam)."],
  ["Письмо уже отправляли недавно. Подожди минутку и попробуй снова.", "Лист уже надсилали недавно. Зачекай хвилинку й спробуй знову.", "An email was already sent recently. Wait a minute and try again."],
  ["Повторите пароль", "Повторіть пароль", "Repeat password"],
  ["Подготовка…", "Підготовка…", "Preparing…"],
  ["Поддержка", "Підтримка", "Support"],
  ["Поделиться профилем", "Поділитися профілем", "Share profile"],
  ["Подключено", "Підключено", "Connected"],
  ["Подписка активна", "Підписка активна", "Subscription active"],
  ["Подписка оформлена & Пасхалка открыта! 🎉", "Підписку оформлено & Великодку відкрито! 🎉", "Subscription Activated & Easter Egg Unlocked! 🎉"],
  ["Подпись", "Підпис", "Signature"],
  ["Подтвердите email адрес", "Підтвердіть email адресу", "Confirm your email address"],
  ["Подтвердите новый email", "Підтвердіть новий email", "Confirm new email"],
  ["Подтвердите письмо на новом адресе, затем начнётся 24-часовое ожидание.", "Підтвердіть лист на новій адресі, потім почнеться 24-годинне очікування.", "Confirm the message at the new address, then a 24-hour waiting period begins."],
  ["Подтверждён", "Підтверджено", "Confirmed"],
  ["Подчёркнутый (Ctrl+U)", "Підкреслений (Ctrl+U)", "Underline (Ctrl+U)"],
  ["Поздравляем!", "Вітаємо!", "Congratulations!"],
  ["Поздравляем! Вы активировали 1 Год Premium и открыли секретную пасхалку «Хранитель эпохи»!", "Вітаємо! Ви активували 1 Рік Premium і відкрили секретну великодку «Хранитель епохи»!", "Congratulations! You activated 1 Year of Premium and unlocked the secret 'Epoch Keeper' Easter egg!"],
  ["Поздравляем! Вы активировали 6 месяцев Premium и открыли секретную пасхалку «Сезонный страж»!", "Вітаємо! Ви активували 6 місяців Premium і відкрили секретну великодку «Сезонний страж»!", "Congratulations! You activated 6 Months of Premium and unlocked the secret 'Season Guardian' Easter egg!"],
  ["Поздравляем! Вы активировали бессрочный статус Lifetime VIP и разблокировали легендарную пасхалку «Властелин бесконечности»!", "Вітаємо! Ви активували безстроковий статус Lifetime VIP і розблокували легендарну великодку «Володар нескінченності»!", "Congratulations! You activated Lifetime VIP and unlocked the legendary 'Infinity Overlord' Easter egg!"],
  ["Поздравляем! Вы активировали подписку CybLight Premium и разблокировали секретную пасхалку «Золотое прикосновение»!", "Вітаємо! Ви активували підписку CybLight Premium і розблокували секретну великодку «Золотий дотик»!", "Congratulations! You activated CybLight Premium and unlocked the secret 'Golden Touch' Easter egg!"],
  ["Поздравляем! Вы запустили свой первый месяц Premium и открыли секретную пасхалку «Первый импульс»!", "Вітаємо! Ви запустили свій перший місяць Premium і відкрили секретну великодку «Перший імпульс»!", "Congratulations! You launched your first month of Premium and unlocked the secret 'First Pulse' Easter egg!"],
  ["Поиск пользователей", "Пошук користувачів", "Search users"],
  ["Поиск эмодзи...", "Пошук емодзі...", "Search emoji..."],
  ["Показать панель форматирования", "Показати панель форматування", "Show formatting toolbar"],
  ["Показывать онлайн-статус", "Показувати онлайн-статус", "Show online status"],
  ["Пол", "Стать", "Gender"],
  ["Полгода несокрушимой защиты и премиальной мощи аккаунта 🛡️⚡", "Півроку незламного захисту та преміальної могутності акаунта 🛡️⚡", "Half a year of impenetrable defense and premium power for your account 🛡️⚡"],
  ["Получи бессрочный доступ ко всем возможностям экосистемы CybLight навсегда", "Отримай безстроковий доступ до всіх можливостей екосистеми CybLight назавжди", "Get lifetime access to all capabilities of the CybLight ecosystem forever"],
  ["Пользователь с таким именем не найден.", "Користувача з таким ім'ям не знайдено.", "User with this name was not found."],
  ["Пользователь с такими данными уже существует.", "Користувач із такими даними вже існує.", "A user with these credentials already exists."],
  ["Пользователь:", "Користувач:", "User:"],
  ["Помощник", "Помічник", "Helper"],
  ["Помощь с регистрацией и верификацией новых участников сообщества.", "Допомога з реєстрацією та верифікацією нових учасників спільноти.", "Help with registration and verification of new community members."],
  ["Понятно", "Зрозуміло", "Got it"],
  ["Попробуй найти скрытую реакцию на элементы своего профиля", "Спробуй знайти приховану реакцію на елементи свого профілю", "Try to discover hidden reactions on your profile elements"],
  ["Попробуйте изменить запрос", "Спробуйте змінити запит", "Try changing your search"],
  ["Популярный выбор", "Популярний вибір", "Popular choice"],
  ["Последнее сохранение", "Останнє збереження", "Last saved"],
  ["Последний вход", "Останній вхід", "Last sign-in"],
  ["Последний вход:", "Останній вхід:", "Last sign-in:"],
  ["Последний раз был изменён:", "Останній раз змінювався:", "Last changed:"],
  ["Последняя активность", "Остання активність", "Last activity"],
  ["Постоянный", "Постійний", "Permanent"],
  ["Предпросмотр", "Попередній перегляд", "Preview"],
  ["Предпросмотр ссылки", "Попередній перегляд посилання", "Link preview"],
  ["Премиум темы", "Преміум теми", "Premium themes"],
  ["При входе потребуется код из приложения аутентификатора.", "При вході знадобиться код з додатка автентифікатора.", "You will need a code from your authenticator app when signing in."],
  ["Прикоснись к миру эксклюзивных возможностей и премиального статуса", "Доторкнися до світу ексклюзивних можливостей та преміального статусу", "Touch the world of exclusive capabilities and premium status"],
  ["Принято ✦", "Прийнято ✦", "Accepted ✦"],
  ["Приоритетная E2EE-синхронизация", "Пріоритетна E2EE-синхронізація", "Priority E2EE synchronization"],
  ["Приоритетная поддержка", "Пріоритетна підтримка", "Priority support"],
  ["Причина:", "Причина:", "Reason:"],
  ["Проверенный ресурс:", "Перевірений ресурс:", "Verified resource:"],
  ["Проверка безопасности", "Перевірка безпеки", "Security check"],
  ["Проверка безопасности не пройдена. Пожалуйста, повторите попытку.", "Перевірка безпеки не пройдена. Будь ласка, повторіть спробу.", "Security check failed. Please try again."],
  ["Проверка...", "Перевірка...", "Checking..."],
  ["Проверяем секрет...", "Перевіряємо секрет...", "Checking secret..."],
  ["Проверяю...", "Перевіряю...", "Verifying..."],
  ["Продлить через Stripe", "Продовжити через Stripe", "Renew with Stripe"],
  ["Произошла ошибка при выполнении запроса", "Сталася помилка під час виконання запиту", "An error occurred while processing the request"],
  ["Произошла ошибка при сохранении", "Сталася помилка під час збереження", "An error occurred while saving"],
  ["Пропустить", "Пропустити", "Skip"],
  ["Просмотр активности аккаунта", "Перегляд активності облікового запису", "View account activity"],
  ["Профиль виден другим пользователям", "Профіль видно іншим користувачам", "Profile is visible to other users"],
  ["Профиль пользователя", "Профіль користувача", "User profile"],
  ["Прочитано", "Прочитано", "Read"],
  ["Прямой доступ к разработчикам 24/7", "Прямий доступ до розробників 24/7", "Direct 24/7 access to developers"],
  ["Разгадай загадку тьмы, припрятанную где-то на сайте", "Розгадай загадку темряви, приховану десь на сайті", "Solve the riddle of darkness hidden somewhere on the site"],
  ["Разработчик", "Розробник", "Developer"],
  ["Рамка аватара", "Рамка аватара", "Avatar frame"],
  ["Ранний доступ к новым функциям и возможность сообщать об ошибках до публичного релиза.", "Ранній доступ до нових функцій і можливість повідомляти про помилки до публічного релізу.", "Early access to new features and the ability to report bugs before public release."],
  ["Расскажите о себе подробнее (до 1000 символов)...", "Розкажіть про себе детальніше (до 1000 символів)...", "Tell us more about yourself (up to 1000 characters)..."],
  ["Расширенные настройки уведомлений появятся в ближайшее время", "Розширені налаштування повідомлень зʼявляться найближчим часом", "Advanced notification settings will be available soon"],
  ["Расширенные права управления платформой и её настройками.", "Розширені права керування платформою та її налаштуваннями.", "Extended rights to manage the platform and its settings."],
  ["Регистратор", "Реєстратор", "Registrar"],
  ["Регистрация ключа отменена", "Реєстрацію ключа скасовано", "Key registration cancelled"],
  ["Редактирование сообщения...", "Редагування повідомлення...", "Editing message..."],
  ["Редкая пасхалка для тех, кто не боится консоли.", "Рідкісна пасхалка для тих, хто не боїться консолі.", "A rare easter egg for those who are not afraid of the console."],
  ["Редкие пасхалки", "Рідкісні пасхалки", "Rare Easter eggs"],
  ["Редкий секрет для самых внимательных", "Рідкісний секрет для найуважніших", "A rare secret for the most attentive"],
  ["Редкий секрет из почтового ящика добавлен в коллекцию пасхалок.", "Рідкісний секрет із поштової скриньки додано до колекції пасхалок.", "A rare inbox secret was added to your easter egg collection."],
  ["Резервная копия", "Резервна копія", "Backup"],
  ["Резервная копия ключей и сообщений — в разделе «Безопасность → Резервная копия» (Google Drive или файл).", "Резервна копія ключів і повідомлень — у розділі «Безопека → Резервна копія» (Google Drive або файл).", "Backup of keys and messages is in Security → Backup (Google Drive or file)."],
  ["Резервная копия сохранена (ключи и сообщения).", "Резервну копію збережено (ключі й повідомлення).", "Backup saved (keys and messages)."],
  ["Резервная копия сохранена в Google Drive.", "Резервну копію збережено в Google Drive.", "Backup saved to Google Drive."],
  ["Резервная копия удалена из Google Drive.", "Резервну копію видалено з Google Drive.", "Backup deleted from Google Drive."],
  ["Резервная копия чатов", "Резервна копія чатів", "Chat backup"],
  ["Резервная копия шифрования", "Резервна копія шифрування", "Encryption backup"],
  ["Резервные коды:", "Резервні коди:", "Backup codes:"],
  ["Русский", "Російська", "Russian"],
  ["Свернуть", "Згорнути", "Collapse"],
  ["Свет спрятан в мобильном приложении CybLight", "Світ сховано в мобільному додатку CybLight", "The light is hidden in the CybLight mobile app"],
  ["Связаться с администрацией", "Звʼязатися з адміністрацією", "Contact administration"],
  ["Связующие", "Звʼязуючі", "Connectors"],
  ["Сделай первый решительный шаг в мир премиальных технологий", "Зроби перший рішучий крок у світ преміальних технологій", "Take the first decisive step into the world of premium technology"],
  ["Сегодня", "Сьогодні", "Today"],
  ["Сезонный страж", "Сезонний страж", "Season Guardian"],
  ["Секрет для тех, кто не может выбрать одну тему", "Секрет для тих, хто не може обрати одну тему", "A secret for those who cannot pick one theme"],
  ["Секрет спрятан там, где заканчиваются автоматические письма", "Секрет сховано там, де закінчуються автоматичні листи", "The secret is hidden where automated emails end"],
  ["Секрет спрятан там, где ты показываешь себя миру", "Секрет схований там, де ти показуєш себе світу", "The secret is hidden where you show yourself to the world"],
  ["Секретная пасхалка найдена!", "Секретну великодку знайдено!", "Secret Easter egg found!"],
  ["Секретное достижение разблокировано", "Секретне досягнення розблоковано", "Secret achievement unlocked"],
  ["Секретный ключ:", "Секретний ключ:", "Secret key:"],
  ["Секретный ритм найден! ✨", "Секретний ритм знайдено! ✨", "Secret rhythm found! ✨"],
  ["Семь отражений — и ты увидел себя с другой стороны", "Сім відображень — і ти побачив себе з іншого боку", "Seven reflections — and you saw yourself from another side"],
  ["Сессия Google Drive завершена.", "Сесію Google Drive завершено.", "Google Drive session ended."],
  ["Сессия завершена ✅", "Сесію завершено ✅", "Session ended ✅"],
  ["Сессия истекла. Пожалуйста, войдите в аккаунт заново.", "Сесія закінчилася. Будь ласка, увійдіть в акаунт знову.", "Session expired. Please sign in to your account again."],
  ["Символы", "Символи", "Symbols"],
  ["Системные уведомления", "Системні повідомлення", "System notifications"],
  ["Скачать .cyblight-backup", "Завантажити .cyblight-backup", "Download .cyblight-backup"],
  ["Скачать приложение", "Завантажити додаток", "Download app"],
  ["Скопировать ID пользователя", "Скопіювати ID користувача", "Copy user ID"],
  ["Скоро", "Скоро", "Soon"],
  ["Скрывать напоминание о резервной копии", "Приховувати нагадування про резервну копію", "Hide backup reminder"],
  ["Скрывать панель форматирования по умолчанию", "Приховувати панель форматування за замовчуванням", "Hide formatting toolbar by default"],
  ["Скрыть панель форматирования", "Приховати панель форматування", "Hide formatting toolbar"],
  ["Слишком много запросов. Пожалуйста, подождите немного и попробуйте снова.", "Забагато запитів. Будь ласка, зачекайте трохи і спробуйте знову.", "Too many requests. Please wait a moment and try again."],
  ["Слишком много попыток. Подожди и попробуй снова.", "Забагато спроб. Зачекай і спробуй знову.", "Too many attempts. Wait and try again."],
  ["Смайлики", "Смайлики", "Emoji"],
  ["Смайлики для бейджа", "Смайлики для бейджа", "Badge emojis"],
  ["Смена email завершится скоро", "Зміну email скоро завершиться", "Email change completes soon"],
  ["Смена email отменена", "Зміну email скасовано", "Email change cancelled"],
  ["Смена запланирована", "Зміну заплановано", "Change scheduled"],
  ["Смена подтверждённого email требует пароль{twoFA}. Новый адрес вступит в силу через 24 часа после подтверждения.", "Зміна підтвердженого email потребує пароль{twoFA}. Нова адреса набуде чинності за 24 години після підтвердження.", "Changing a confirmed email requires a password{twoFA}. The new address takes effect 24 hours after confirmation."],
  ["Сменить пароль", "Змінити пароль", "Change password"],
  ["Собеседник", "Співрозмовник", "Chat partner"],
  ["Создан:", "Створено:", "Created:"],
  ["Создание сессии Stripe...", "Створення сесії Stripe...", "Creating Stripe session..."],
  ["Создано в системе", "Створено в системі", "Created in the system"],
  ["Сообщение", "Повідомлення", "Message"],
  ["Сообщение откреплено", "Повідомлення відкріплено", "Message unpinned"],
  ["Сообщение переслано", "Повідомлення переслано", "Message forwarded"],
  ["Сообщение ушло в полночь — эхо услышано", "Повідомлення пішло опівночі — ехо почуто", "Message sent at midnight — echo heard"],
  ["Сообщения защищены шифрованием", "Повідомлення захищені шифруванням", "Messages are encrypted"],
  ["Сохранение в Google Drive…", "Збереження в Google Drive…", "Saving to Google Drive…"],
  ["Сохранение и восстановление только ключей шифрования в Google Drive. Доступ только у приложения CybLight и только к созданным им файлам.", "Збереження та відновлення лише ключів шифрування в Google Drive. Доступ має тільки застосунок CybLight і лише до створених ним файлів.", "Stores and restores only encryption keys in Google Drive. Access is restricted to CybLight and only to files created by it."],
  ["Сохранение…", "Збереження…", "Saving…"],
  ["Сохрани эти резервные коды в безопасном месте. Каждый можно использовать только один раз.", "Збережи ці резервні коди в безпечному місці. Кожен можна використати лише один раз.", "Save these backup codes in a safe place. Each can only be used once."],
  ["Сохраните переписку в файл или восстановите её из резервной копии этого аккаунта.", "Збережіть листування у файл або відновіть його з резервної копії цього облікового запису.", "Save chats to a file or restore them from this account's backup."],
  ["Сохраните резервную копию ключей в разделе «Безопасность».", "Збережіть резервну копію ключів у розділі «Безпека».", "Save an encryption key backup in Security."],
  ["Сохраните резервную копию ключей, чтобы не потерять доступ к переписке при смене устройства или браузера.", "Збережіть резервну копію ключів, щоб не втратити доступ до листування під час зміни пристрою або браузера.", "Save an encryption key backup so you don't lose access to chats when switching devices or browsers."],
  ["Сохранить в Google Drive", "Зберегти в Google Drive", "Save to Google Drive"],
  ["Сохраняю...", "Зберігаю...", "Saving..."],
  ["Сохраняю…", "Зберігаю…", "Saving…"],
  ["Спойлер (Ctrl+Shift+P)", "Спойлер (Ctrl+Shift+P)", "Spoiler (Ctrl+Shift+P)"],
  ["Средняя", "Середня", "Medium"],
  ["Ссылка на Профиль скопирована", "Посилання на профіль скопійовано", "Profile link copied"],
  ["Стандартный доступ к сайту: профиль, сообщения и участие в проектах CybLight.", "Стандартний доступ до сайту: профіль, повідомлення та участь у проєктах CybLight.", "Standard site access: profile, messages, and participation in CybLight projects."],
  ["Статус", "Статус", "Status"],
  ["Статус аккаунта", "Статус облікового запису", "Account status"],
  ["Стиль", "Стиль", "Style"],
  ["Сто раз подтвердил вход биометрией", "Сто раз підтвердив вхід біометрією", "Confirmed sign-in with biometrics 100 times"],
  ["Также закрепить для собеседника", "Також закріпити для співрозмовника", "Also pin for chat partner"],
  ["Текст бейджа", "Текст бейджа", "Badge text"],
  ["Текст бейджа содержит недопустимые или 18+ выражения", "Текст бейджа містить неприпустимі або 18+ вирази", "Badge text contains prohibited or 18+ terms"],
  ["Текст содержит недопустимые или 18+ выражения.", "Текст містить неприпустимі або 18+ вирази.", "Text contains prohibited or 18+ terms."],
  ["Текст ссылки:", "Текст посилання:", "Link text:"],
  ["Текущая", "Поточна", "Current"],
  ["Текущее имя пользователя", "Поточне ім'я користувача", "Current username"],
  ["Текущий пароль", "Поточний пароль", "Current password"],
  ["Тема оформления", "Тема оформлення", "Interface theme"],
  ["Тестер", "Тестер", "Tester"],
  ["Только друзьям", "Лише друзям", "Friends only"],
  ["Ты бодрствуешь в тёмной теме после полуночи", "Ти пильнуєш у темній темі після опівночі", "You stay awake in dark theme after midnight"],
  ["Ты заглянул в самый низ письма — туда, куда почти никто не смотрит.", "Ти заглянув у самий низ листа — туди, куди майже ніхто не дивиться.", "You looked at the very bottom of the email — where almost nobody looks."],
  ["Ты заглянул под капот и поймал бегущую строку.", "Ти заглянув під капот і спіймав бігучий рядок.", "You looked under the hood and caught the marquee."],
  ["Ты заметил тёмный триггер в полной темноте! Редкое достижение 🌟", "Ти помітив темний тригер у повній темряві! Рідкісне досягнення 🌟", "You noticed the dark trigger in complete darkness! Rare achievement 🌟"],
  ["Ты запустил свой первый месяц Premium и начал путь к вершине CybLight 🚀", "Ти запустив свій перший місяць Premium і розпочав шлях до вершини CybLight 🚀", "You launched your first month of Premium and began your journey to the summit of CybLight 🚀"],
  ["Ты нашел особую клубничку на сайте! Отличная работа 🎉", "Ти знайшов особливу полуничку на сайті! Чудова робота 🎉", "You found a special strawberry on the site! Great job 🎉"],
  ["Ты обрел статус CybLight Premium и золотое сияние превосходства 👑✨", "Ти здобув статус CybLight Premium і золоте сяйво досконалості 👑✨", "You achieved CybLight Premium status and the golden radiance of excellence 👑✨"],
  ["Ты открыл DevTools и поймал бегущую строку в футере", "Ти відкрив DevTools і спіймав бігучий рядок у футері", "You opened DevTools and caught the footer marquee"],
  ["Ты открыл секретный неоновый режим и квантовое сияние профиля 🎨✨", "Ти відкрив секретний неоновий режим і квантове сяйво профілю 🎨✨", "You unlocked the secret neon mode and quantum profile radiance 🎨✨"],
  ["Ты поймал свет в приложении CybLight! Быстрые пальцы ⚡", "Ти спіймав світ у додатку CybLight! Швидкі пальці ⚡", "You caught the light in the CybLight app! Fast fingers ⚡"],
  ["Ты пробудил звёздный вихрь и тайную силу своего бейджа ⭐💫", "Ти пробудив зоряний вихор і таємну силу свого бейджа ⭐💫", "You awakened the stellar vortex and the secret power of your badge ⭐💫"],
  ["Ты прочитал письмо до самого конца — настоящий почтовый детектив", "Ти прочитав лист до самого кінця — справжній поштовий детектив", "You read the email to the very end — a true mail detective"],
  ["Ты раскачал сайт между светом и тьмой — настроение поймано", "Ти розгойдав сайт між світлом і темрявою — настрій спіймано", "You swung the site between light and dark — mood caught"],
  ["Тёмная", "Темна", "Dark"],
  ["У вас пока нет друзей", "У вас поки немає друзів", "You have no friends yet"],
  ["Убрать закреп из этого чата?", "Прибрати закріплення з цього чату?", "Remove pin from this chat?"],
  ["Уведомления", "Повідомлення", "Notifications"],
  ["Уведомления о новых запросах дружбы", "Повідомлення про нові запити дружби", "Friend request notifications"],
  ["Уведомления о новых сообщениях от друзей", "Повідомлення про нові повідомлення від друзів", "Message notifications from friends"],
  ["Удаление аккаунта", "Видалення акаунту", "Account deletion"],
  ["Удаление доверенного устройства", "Видалення довіреного пристрою", "Remove trusted device"],
  ["Удаление друга", "Видалення друга", "Remove friend"],
  ["Удалено {count} сообщений", "Видалено {count} повідомлень", "Deleted {count} messages"],
  ["Удалить {count} выбранных сообщений?", "Видалити {count} вибраних повідомлень?", "Delete {count} selected messages?"],
  ["Удалить аккаунт", "Видалити акаунт", "Delete account"],
  ["Удалить из Drive", "Видалити з Drive", "Delete from Drive"],
  ["Удалить копию из Google Drive?", "Видалити копію з Google Drive?", "Delete backup from Google Drive?"],
  ["Удалить предпросмотр", "Видалити попередній перегляд", "Remove preview"],
  ["Удалить сообщения", "Видалити повідомлення", "Delete messages"],
  ["Удалить это доверенное устройство?", "Видалити цей довірений пристрій?", "Remove this trusted device?"],
  ["Удалить этот ключ доступа?", "Видалити цей ключ доступу?", "Remove this passkey?"],
  ["Уникальный бейдж рядом с никнеймом (до 24 символов, только для Premium)", "Унікальний бейдж поруч із нікнеймом (до 24 символів, тільки для Premium)", "Unique badge next to your username (up to 24 chars, Premium only)"],
  ["Управление", "Керування", "Management"],
  ["Управление email-уведомлениями", "Керування email-повідомленнями", "Email notifications management"],
  ["Управление аккаунтом", "Керування обліковим записом", "Account management"],
  ["Управление данными и настройками приватности", "Керування даними та налаштуваннями конфіденційності", "Data & privacy settings management"],
  ["Управление паролем, двухфакторной аутентификацией и сессиями", "Керування паролем, двофакторною автентифікацією та сесіями", "Password, 2FA & sessions management"],
  ["Управление устройствами для входа с 2FA", "Керування пристроями для входу з 2FA", "Manage devices for 2FA sign-in"],
  ["Управление устройствами, с которых выполнен вход", "Керування пристроями, з яких виконано вхід", "Logged-in devices management"],
  ["Уровень защиты:", "Рівень захисту:", "Security level:"],
  ["Устройства", "Пристрої", "Devices"],
  ["Устройство", "Пристрій", "Device"],
  ["Устройство удалено", "Пристрій видалено", "Device removed"],
  ["Устройство успешно привязано! Ключи шифрования синхронизированы.", "Пристрій успішно привʼязано! Ключі шифрування синхронізовано.", "Device successfully linked! Encryption keys synchronized."],
  ["Устройство:", "Пристрій:", "Device:"],
  ["Файл будет удалён из вашего Google Drive. Локальные ключи и сообщения не пострадают.", "Файл буде видалено з вашого Google Drive. Локальні ключі й повідомлення не постраждають.", "The file will be deleted from your Google Drive. Local keys and messages will not be affected."],
  ["Форма для отправки сообщения администратору", "Форма для надсилання повідомлення адміністратору", "Form to send a message to the administrator"],
  ["Хранилище Google", "Сховище Google", "Google Storage"],
  ["Хранитель эпохи", "Хранитель епохи", "Epoch Keeper"],
  ["Целый год неограниченной свободы, высших лимитов и почета 🏛️⌛", "Цілий рік необмеженої свободи, найвищих лімітів та шани 🏛️⌛", "A full year of unlimited freedom, top limits, and prestige 🏛️⌛"],
  ["Цитата (Ctrl+Shift+Q)", "Цитата (Ctrl+Shift+Q)", "Quote (Ctrl+Shift+Q)"],
  ["Чаты: добавлено {imported}, пропущено {skipped}.", "Чати: додано {imported}, пропущено {skipped}.", "Chats: added {imported}, skipped {skipped}."],
  ["Черновик", "Чернетка", "Draft"],
  ["Что входит в подписку:", "Що входить до підписки:", "What is included in the subscription:"],
  ["Шаг 1: Отсканируй QR-код", "Крок 1: Відскануй QR-код", "Step 1: Scan the QR code"],
  ["Шаг 2: Введи код из приложения", "Крок 2: Введи код з додатка", "Step 2: Enter the code from the app"],
  ["Эксклюзив", "Ексклюзив", "Exclusive"],
  ["Эксклюзивные аватары", "Ексклюзивні аватари", "Exclusive avatars"],
  ["Эксклюзивные неоновые и анимированные рамки для подписчиков CybLight Premium.", "Ексклюзивні неонові та анімовані рамки для підписників CybLight Premium.", "Exclusive neon and animated frames for CybLight Premium subscribers."],
  ["Эксклюзивные темы и аватары", "Ексклюзивні теми та аватари", "Exclusive themes and avatars"],
  ["Эксклюзивный значок в профиле, чатах и SmartHome Hub", "Ексклюзивний значок у профілі, чатах та SmartHome Hub", "Exclusive badge in profile, chats, and SmartHome Hub"],
  ["Экспорт", "Експорт", "Export"],
  ["Экспорт и импорт ключей шифрования между устройствами", "Експорт і імпорт ключів шифрування між пристроями", "Export and import encryption keys between devices"],
  ["Экспорт и импорт чатов", "Експорт і імпорт чатів", "Export and import chats"],
  ["Экспорт чатов", "Експорт чатів", "Export chats"],
  ["Экспортировано чатов: {chats}, сообщений: {messages}", "Експортовано чатів: {chats}, повідомлень: {messages}", "Exported chats: {chats}, messages: {messages}"],
  ["Электронная почта", "Електронна пошта", "Email"],
  ["Электронная почта успешно обновлена", "Електронну пошту успішно оновлено", "Email successfully updated"],
  ["Эта копия создана для другого аккаунта.", "Ця копія створена для іншого облікового запису.", "This backup was created for a different account."],
  ["Это закрытый профиль", "Це закритий профіль", "This is a private profile"],
  ["Это имя пользователя зарезервировано администрацией сайта", "Це ім'я користувача зарезервовано адміністрацією сайту", "This username is reserved by site administration"],
  ["Это имя пользователя зарезервировано администрацией сайта. Пожалуйста, выберите другое имя.", "Це ім'я користувача зарезервовано адміністрацією сайту. Будь ласка, оберіть інше ім'я.", "This username is reserved by site administration. Please choose another username."],
  ["Это имя пользователя уже занято", "Це імʼя користувача вже зайнято", "This username is already taken"],
  ["Это имя пользователя уже занято. Пожалуйста, выберите другое имя.", "Це ім'я користувача вже зайняте. Будь ласка, оберіть інше ім'я.", "This username is already taken. Please choose another username."],
  ["Это проверенный ресурс, который заслуживает доверия — здесь можно найти достоверную информацию и ответы на многие жизненные вопросы.", "Це перевірений ресурс, який заслуговує на довіру — тут можна знайти достовірну інформацію та відповіді на багато життєвих питань.", "This is a verified trustworthy resource offering reliable information and answers to many life questions."],
  ["Это профиль пользователя. Дополнительная информация скоро будет доступна.", "Це профіль користувача. Додаткова інформація незабаром буде доступна.", "This is a user profile. More information will be available soon."],
  ["Это текущий email. Введите другой адрес.", "Це поточний email. Введіть іншу адресу.", "This is your current email. Enter a different address."],
  ["Этот адрес электронной почты уже зарегистрирован в системе.", "Ця адреса електронної пошти вже зареєстрована в системі.", "This email address is already registered in the system."],
  ["Этот адрес электронной почты уже используется.", "Ця адреса електронної пошти вже використовується.", "This email address is already in use."],
  ["Этот аккаунт заблокирован.", "Цей акаунт заблоковано.", "This account has been banned."],
  ["Эхо", "Ехо", "Echo"],
  ["Язык и тема интерфейса", "Мова та тема інтерфейсу", "Interface language & theme"],
  ["Язык интерфейса", "Мова інтерфейсу", "Interface language"],
  ["Язык программирования (необязательно):", "Мова програмування (необовʼязково):", "Programming language (optional):"],
  ["друзей", "друзів", "friends"],
  ["не существует", "не існує", "does not exist"],
  ["обязательное поле", "обовʼязкове поле", "required field"],
  ["осталось", "залишилося", "remaining"],
  ["по умолчанию", "за замовчуванням", "default"],
  ["пользователя", "користувача", "user"],
  ["скоро", "незабаром", "soon"],
  ["сообщение", "повідомлення", "message"],
  ["через {hours} ч {minutes} мин", "через {hours} год {minutes} хв", "in {hours} h {minutes} min"],
  ["через {minutes} мин", "через {minutes} хв", "in {minutes} min"],
  ["— Email не указан", "— Email не вказано", "— Email not set"],
  ["• Администратор", "• Адміністратор", "• Administrator"],
  ["• Владелец", "• Власник", "• Owner"],
  ["• Модератор", "• Модератор", "• Moderator"],
  ["• Поддержка", "• Підтримка", "• Support"],
  ["• Регистратор", "• Реєстратор", "• Registrar"],
  ["• Тестер", "• Тестер", "• Tester"],
  ["← Вернуться к входу", "← Повернутися до входу", "← Back to sign in"],
  ["↪️ Переслать", "↪️ Переслати", "↪️ Forward"],
  ["⏳ Email сменится на", "⏳ Email зміниться на", "⏳ Email will change to"],
  ["⏳ Ожидается подтверждение", "⏳ Очікується підтвердження", "⏳ Awaiting confirmation"],
  ["⏳ Ожидание ответа", "⏳ Очікування відповіді", "⏳ Awaiting response"],
  ["⚠️ Email не подтверждён", "⚠️ Email не підтверджено", "⚠️ Email not confirmed"],
  ["⚠️ Ошибка при поиске", "⚠️ Помилка під час пошуку", "⚠️ Search error"],
  ["✅ Email подтверждён", "✅ Email підтверджено", "✅ Email confirmed"],
  ["✅ {username} добавлен в друзья!", "✅ {username} додано в друзі!", "✅ {username} added as a friend!"],
  ["✅ Включена", "✅ Увімкнено", "✅ Enabled"],
  ["✅ Запрос отправлен пользователю {username}!", "✅ Запит надіслано користувачу {username}!", "✅ Request sent to {username}!"],
  ["✅ Принять", "✅ Прийняти", "✅ Accept"],
  ["✅ Успешный вход", "✅ Успішний вхід", "✅ Successful sign-in"],
  ["✓ Найдено", "✓ Знайдено", "✓ Found"],
  ["✕ Отменить", "✕ Скасувати", "✕ Cancel"],
  ["❌ WebAuthn недоступен в этом контексте. Откройте сайт через https:// или http://localhost / http://127.0.0.1.", "❌ WebAuthn недоступний у цьому контексті. Відкрийте сайт через https:// або http://localhost / http://127.0.0.1.", "❌ WebAuthn is unavailable in this context. Open the site via https:// or http://localhost / http://127.0.0.1."],
  ["❌ WebAuthn требует безопасный контекст.\\n\\nОткройте страницу на https:// или локально через http://localhost или http://127.0.0.1 (не через IP сети и не в iframe).", "❌ WebAuthn потребує безпечного контексту.\\n\\nВідкрийте сторінку на https:// або локально через http://localhost чи http://127.0.0.1 (не через IP мережі та не в iframe).", "❌ WebAuthn requires a secure context.\\n\\nOpen the page on https:// or locally via http://localhost or http://127.0.0.1 (not via network IP or inside an iframe)."],
  ["❌ Запрос от {username} отклонён", "❌ Запит від {username} відхилено", "❌ Request from {username} declined"],
  ["❌ Неудачный вход", "❌ Невдалий вхід", "❌ Failed sign-in"],
  ["❌ Отклонить", "❌ Відхилити", "❌ Decline"],
  ["❌ Отмена", "❌ Скасування", "❌ Cancel"],
  ["❌ Отменить", "❌ Скасувати", "❌ Cancel"],
  ["❌ Удалить", "❌ Видалити", "❌ Delete"],
  ["➕ Passkey добавлен", "➕ Passkey додано", "➕ Passkey added"],
  ["➕ Добавить", "➕ Додати", "➕ Add"],
  ["➕ Добавить ключ доступа", "➕ Додати ключ доступу", "➕ Add passkey"],
  ["➖ Passkey удалён", "➖ Passkey видалено", "➖ Passkey removed"],
  ["⭐ Эксклюзивные рамки аватара доступны только для подписчиков CybLight Premium", "⭐ Ексклюзивні рамки аватара доступні лише для підписників CybLight Premium", "⭐ Exclusive avatar frames are available only to CybLight Premium subscribers"],
  ["🆕 Аккаунт создан", "🆕 Обліковий запис створено", "🆕 Account created"],
  ["🎉 Превосходно!", "🎉 Чудово!", "🎉 Excellent!"],
  ["🎊 CybLight на обоих берегах!", "🎊 CybLight на обох берегах!", "🎊 CybLight on both shores!"],
  ["🎊 Вечный статус навсегда вписан в историю!", "🎊 Вічний статус назавжди вписано в історію!", "🎊 Eternal status inscribed into history forever!"],
  ["🎊 Годовая эпоха под контролем!", "🎊 Річна епоха під контролем!", "🎊 Annual epoch under control!"],
  ["🎊 Звёздный мастер пробуждён!", "🎊 Зоряний майстер пробуджений!", "🎊 Stellar Master Awakened!"],
  ["🎊 Золотой статус активирован!", "🎊 Золотий статус активовано!", "🎊 Golden status activated!"],
  ["🎊 Конгратулейшн, ты настоящий детектив!", "🎊 Вітаємо, ти справжній детектив!", "🎊 Congrats, you are a real detective!"],
  ["🎊 Месячный импульс на максимуме!", "🎊 Місячний імпульс на максимумі!", "🎊 Monthly pulse at maximum!"],
  ["🎊 Поздравляем с находкой!", "🎊 Вітаємо з знахідкою!", "🎊 Congratulations on your find!"],
  ["🎊 Полугодовой щит активен!", "🎊 Піврічний щит активний!", "🎊 Half-year shield active!"],
  ["🎊 Свет пойман — секрет сохранён!", "🎊 Світ спіймано — секрет збережено!", "🎊 Light caught — secret saved!"],
  ["🎊 Свет ↔ тьма — и секрет ваш!", "🎊 Світ ↔ темрява — і секрет ваш!", "🎊 Light ↔ dark — and the secret is yours!"],
  ["🎊 Секрет из ящика входящих пойман!", "🎊 Секрет із вхідних спіймано!", "🎊 Inbox secret caught!"],
  ["🎊 Творческий потенциал разблокирован!", "🎊 Творчий потенціал розблоковано!", "🎊 Creative potential unlocked!"],
  ["🎊 Ты заглянул в своё отражение!", "🎊 Ти заглянув у своє відображення!", "🎊 You looked into your reflection!"],
  ["🎊 Формат отражён на обеих платформах!", "🎊 Формат відображено на обох платформах!", "🎊 Format applied on both platforms!"],
  ["🎯 Пасхалки открываются, когда ты находишь секреты на сайте и в приложении", "🎯 Пасхалки відкриваються, коли ти знаходиш секрети на сайті й у додатку", "🎯 Easter eggs unlock when you find secrets on the site and in the app"],
  ["👤 Профиль", "👤 Профіль", "👤 Profile"],
  ["💡 Подсказка: Загляни под капот сайта", "💡 Підказка: заглянь під капот сайту", "💡 Hint: look under the site hood"],
  ["💡 Подсказка: активируй бессрочный тариф Premium Навсегда", "💡 Підказка: активуй безстроковий тариф Premium Назавжди", "💡 Hint: activate the Lifetime Premium plan"],
  ["💡 Подсказка: верхушка карандаша скрывает ритм творчества...", "💡 Підказка: верхівка олівця приховує ритм творчості...", "💡 Hint: the tip of the pencil hides the rhythm of creativity..."],
  ["💡 Подсказка: включи тёмную тему после 00:00 и останься в приложении", "💡 Підказка: увімкни темну тему після 00:00 і залишся в додатку", "💡 Hint: enable dark theme after 00:00 and stay in the app"],
  ["💡 Подсказка: жирный, курсив или другой стиль — на сайте и в приложении", "💡 Підказка: жирний, курсив або інший стиль — на сайті та в додатку", "💡 Tip: bold, italic or other style — on site and in app"],
  ["💡 Подсказка: загляни в письмо о восстановлении пароля...", "💡 Підказка: заглянь у лист про відновлення пароля...", "💡 Hint: look in the password recovery email..."],
  ["💡 Подсказка: загляни в свой профиль и посмотри на себя чаще...", "💡 Підказка: заглянь у свій профіль і дивись на себе частіше...", "💡 Hint: check your profile and look at yourself more often..."],
  ["💡 Подсказка: закрепи, измени, поставь реакцию и перешли в одном чате", "💡 Підказка: закріпи, зміни, постав реакцію й перешли в одному чаті", "💡 Hint: pin, edit, react, and forward in one chat"],
  ["💡 Подсказка: исследуй сайт и приложение в один день", "💡 Підказка: досліди сайт і додаток за один день", "💡 Hint: explore the site and app in one day"],
  ["💡 Подсказка: исследуй страницы входа...", "💡 Підказка: досліджуй сторінки входу...", "💡 Hint: explore the sign-in pages..."],
  ["💡 Подсказка: оформи подписку Premium на 1 Год", "💡 Підказка: оформи підписку Premium на 1 Рік", "💡 Hint: subscribe to 1 Year of Premium"],
  ["💡 Подсказка: оформи подписку Premium на 1 Месяц", "💡 Підказка: оформи підписку Premium на 1 Місяць", "💡 Hint: subscribe to 1 Month of Premium"],
  ["💡 Подсказка: оформи подписку Premium на 6 Месяцев", "💡 Підказка: оформи підписку Premium на 6 Місяців", "💡 Hint: subscribe to 6 Months of Premium"],
  ["💡 Подсказка: оформи подписку Premium на сайте", "💡 Підказка: оформи підписку Premium на сайті", "💡 Hint: subscribe to Premium on the website"],
  ["💡 Подсказка: поймай минуту перед полуночью в чате", "💡 Підказка: спіймай хвилину перед опівніччю в чаті", "💡 Hint: catch the minute before midnight in chat"],
  ["💡 Подсказка: покачай настроение сайта — свет, тьма, свет...", "💡 Підказка: розгойдай настрій сайту — світ, темрява, світ...", "💡 Hint: swing the site mood — light, dark, light..."],
  ["💡 Подсказка: посмотри в тёмную папку на сайте...", "💡 Підказка: подивись у темну папку на сайті...", "💡 Hint: look into the dark folder on the site..."],
  ["💡 Подсказка: проверь на прочность версию Android приложения", "💡 Підказка: перевір на міцність версію Android-додатку", "💡 Hint: stress-test the Android app version"],
  ["💡 Подсказка: разблокируй приложение отпечатком 100 раз", "💡 Підказка: розблокуй додаток відбитком 100 разів", "💡 Hint: unlock the app with fingerprint 100 times"],
  ["💡 Подсказка: тапни 5 раз подряд по своему бейджу в профиле", "💡 Підказка: тапни 5 разів поспіль по своєму бейджу в профілі", "💡 Hint: tap 5 times in a row on your badge in your profile"],
  ["💡 Рекомендация", "💡 Рекомендація", "💡 Recommendation"],
  ["💬 Написать", "💬 Написати", "💬 Message"],
  ["💾 Скачать", "💾 Завантажити", "💾 Download"],
  ["📋 Копировать все коды", "📋 Копіювати всі коди", "📋 Copy all codes"],
  ["📋 Найдено:", "📋 Знайдено:", "📋 Found:"],
  ["📋 Скопировать ключ", "📋 Скопіювати ключ", "📋 Copy key"],
  ["📖 Открыть стенографию", "📖 Відкрити стенографію", "📖 Open stenography"],
  ["📬 Запрос в друзья", "📬 Запит у друзі", "📬 Friend request"],
  ["📱+ Устройство добавлено", "📱+ Пристрій додано", "📱+ Device added"],
  ["📱- Устройство удалено", "📱- Пристрій видалено", "📱- Device removed"],
  ["🔌 Сессия отозвана", "🔌 Сесію відкликано", "🔌 Session revoked"],
  ["🔍 Поиск пользователей...", "🔍 Пошук користувачів...", "🔍 Searching users..."],
  ["🔍 Пользователи не найдены", "🔍 Користувачів не знайдено", "🔍 No users found"],
  ["🔐 Вход с 2FA", "🔐 Вхід з 2FA", "🔐 Sign-in with 2FA"],
  ["🔑 Вход через passkey", "🔑 Вхід через passkey", "🔑 Sign-in with passkey"],
  ["🔑 Смена пароля", "🔑 Зміна пароля", "🔑 Password change"],
  ["🔒 Закрыто", "🔒 Закрито", "🔒 Closed"],
  ["🔒 Не удалось расшифровать сообщение", "🔒 Не вдалося розшифрувати повідомлення", "🔒 Could not decrypt message"],
  ["🔒 Сообщение недоступно", "🔒 Повідомлення недоступне", "🔒 Message unavailable"],
  ["🔒 Сообщение отправлено", "🔒 Повідомлення надіслано", "🔒 Message sent"],
  ["🔓 2FA отключена", "🔓 2FA вимкнена", "🔓 2FA disabled"],
  ["🔓 Пользователь {name} разблокирован", "🔓 Користувача {name} розблоковано", "🔓 User {name} unblocked"],
  ["🗑️ Удалить", "🗑️ Видалити", "🗑️ Delete"],
  ["🚪 Выход", "🚪 Вихід", "🚪 Sign out"],
  ["🚫 Пользователь {name} заблокирован", "🚫 Користувача {name} заблоковано", "🚫 User {name} blocked"],
  ["🛡️ 2FA включена", "🛡️ 2FA увімкнена", "🛡️ 2FA enabled"],
];
